### ISSUE TITLE
Problem installing transmission

### ISSUE THREAD

**Issue by greekislandlover** [htpcBeginner/AtoMiC-ToolKit#10]
Hi, trying to install this on Ubuntu trusty tahr server. I get the following error:-

--->Making some configuration changes...
sed: can't read /etc/init.d/transmission-daemon: No such file or directory
Replacing daemon username in init failed.
david@ubuntu:~/AtoMiC-ToolKit$

Any ideas please?

**Comment by mildfuzz** [comment]
Getting the exact same issue. The services were not added when installing manually (i.e. without Atomic) either, so my assumption is that is where the issue is.

**Comment by htpcBeginner** [comment]
Latest test with 14.04.03 worked. So closing for now.
