### ISSUE TITLE
Unable to access Sonarr or Radarr (Ubuntu Server 14.04)

### ISSUE THREAD

**Issue by ZaLiTHkA** [htpcBeginner/AtoMiC-ToolKit#104]
**Later on...** For what it's worth; after the messages below, I did configure a new VM with Ubuntu Server 16.04 and AtoMiC ToolKit is working perfectly. :+1: However I would still like to keep this open for the moment, just to get a bit of feedback on my original query anyway.

So in a nutshell, I guess this ticket is now about compatibility with Ubuntu Server 14.04.

---

I suspect this may be somewhat related to issues #64 and #71, since I have the same behaviour as that described in both of them..

Just for clarification, I'm trying to move a bunch of my network services into headless Ubuntu Server VMs, to be run on a single central computer. Using the latest from `master` at the time of writing this note, I just tried to install both Sonarr and Radarr, but after multiple attempts and a few restarts, I am still unable to get them running.

I didn't see any errors during installation so I assumed everything worked correctly, but I get the typical `ERR_CONNECTION_REFUSED` error when trying to access the pages through a browser because the services aren't running. I looked through the shell files that handle installing and configuring the services, worked out how the names are used, but even when I try launch them manually, I get the following:

```sh
media@box-manager:~$ sudo service sonarr start
sonarr: unrecognized service
media@box-manager:~$ sudo service radarr start
radarr: unrecognized service
```

I did notice that Ubuntu Server 14.04 doesn't seem to have an `/opt` directory by default, though I'm not sure why this is. I created this folder and tried again, which resulted in the folders being created correctly during installation:

```sh
media@box-manager:~$ ll /opt/
total 16
drwxr-xr-x  4 root  root  4096 Feb 18 23:36 ./
drwxr-xr-x 22 root  root  4096 Feb 18 23:33 ../
drwxr-xr-x  3 root  root  4096 Feb 18 23:34 NzbDrone/
drwxrwsr-x  4 media media 4096 Feb 18 23:36 radarr/
```

However I still get the same problems. If I check all services, I don't see them in the list at all:

```sh
media@box-template:~$ sudo service --status-all
 [ + ]  acpid
 [ + ]  apparmor
 [ ? ]  apport
 [ + ]  atd
 [ ? ]  binfmt-support
 [ ? ]  console-setup
 [ + ]  cron
 [ - ]  dbus
 [ ? ]  dns-clean
 [ + ]  friendly-recovery
 [ - ]  grub-common
 [ ? ]  irqbalance
 [ ? ]  killprocs
 [ ? ]  kmod
 [ ? ]  networking
 [ + ]  nmbd
 [ ? ]  ondemand
 [ ? ]  pppd-dns
 [ - ]  procps
 [ ? ]  rc.local
 [ + ]  resolvconf
 [ - ]  rsync
 [ + ]  rsyslog
 [ + ]  samba
 [ - ]  samba-ad-dc
 [ ? ]  screen-cleanup
 [ ? ]  sendsigs
 [ + ]  smbd
 [ + ]  ssh
 [ - ]  sudo
 [ + ]  udev
 [ ? ]  umountfs
 [ ? ]  umountnfs.sh
 [ ? ]  umountroot
 [ - ]  unattended-upgrades
 [ - ]  urandom
 [ + ]  winbind
 [ - ]  x11-common
```

Am I doing something wrong here, or is this script simply not compatible with Ubuntu Server?

**Comment by ZaLiTHkA** [comment]
Uh.. Small correction, there is apparently an error during installation. I just tried to install Jackett and I noticed the following at the end of the process:

```sh
--->Autostart configuring...
/home/media/AtoMiC-ToolKit/inc/app-autostart-configure.sh: line 4: systemctl: command not found
\e[91mUnknown startup type.\033[0m

--->Starting Jackett...

--->All done. Jackett installation complete.
For access details, run the Jackett Access Details utility.
```

I'm going to try the other two again now and see if they give the same response.

**Comment by TommyE123** [comment]
Thanks for bring this to my attention. I have to admit I've not done any testing on a 14.0.4 setup so this has been missed so apologies for that. However I'm quietly hoping with a couple of tweaks I can fix this. For starters i'll add a check on the initial script startup to check if the /opt dir doesnt exist then create it. Second i'm hoping I can just tweak the app-autostart-configure.sh script to correctly detect systemd without an error and then just fall back to init.d startup scripts if not supported.

I'm reluctant to start adding loads of upstart scripts as I think pretty much every distro i've looked at has moved to systemd now. Moving to 16 would certainly get round these errors but i still want to try and fix it if i can.

Tom

**Comment by ZaLiTHkA** [comment]
Nothing to apologise for; I'm grateful to have access to a tool like this, just asking questions in the interest of helping resolve strange behaviour and so on. I think the "Compatibility" section in the readme might be slightly outdated at the moment though. (:

In the mean time, I am up and running on my side. Do you think it's worth maintaining scripts for both 14.xx and 16.xx? Not sure what most end users run, so that's a tricky one.

**Comment by TommyE123** [comment]
Sorry I should have put an update on this much sooner. However I've been looking into this issue of older Distros not working. I think every app we have should install and run correctly however I've realised I made a bit to much of an assumption that everyone had the basic packages this tool requires already installed. In the Dev branch that I'm looking to push up to master in the next few days I've added a Toolkit dependencies script which will check on launching the setup.sh file that you have the basic packages installed.

I'm also now hoping after a few changes that the scripts should correctly detect either system or init.d. (I'm not going to support upstart)

For anyone interested the current suggested toolkit dependency package is "**sudo apt-get install apt-transport-https build-essential checkinstall curl dnsutils git mediainfo mediainfo-gui p7zip-full par2 sed software-properties-common sqlite3 tar unzip wget zip -y**"

**Comment by ZaLiTHkA** [comment]
@TommyE123, as per our chat earlier on Gitter, I just checked this again in a Ubuntu Server 14.04.1 VM.

With my local repo updated to the latest (commit a75ab23, at the time of writing this) both Sonarr and Radarr are installed and running without any problems. :) I didn't have to do anything special, I simply cloned the repo and ran `setup.sh` as normal.

**Comment by ZaLiTHkA** [comment]
Since there are a few different services with issues on 14.04, I've changed the title to more accurately reflect this specific issue.

Which is now fixed, as per my previous message.
