### ISSUE TITLE
Failed to start nzbget.service after installation

### ISSUE THREAD

**Issue by thinkbig1979** [htpcBeginner/AtoMiC-ToolKit#105]
Getting this error during install and launch of NZBget.

--->Starting NZBGet...
Failed to start nzbget.service: Unit nzbget.service is not loaded properly: Invalid argument.
See system logs and 'systemctl status nzbget.service' for details.

>:~/AtoMiC-ToolKit$ systemctl status nzbget.service
● nzbget.service - NZBGet Daemon
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)
     Docs: http://nzbget.net/Documentation

Running "sudo service nzbget restart"  results in the same error.

**Comment by thinkbig1979** [comment]
Found the reason:

the systemd script contains these lines:
ExecStart=</path/to/nzbget/nzbget> -D
ExecStop=</path/to/nzbget/nzbget> -Q
ExecReload=</path/to/nzbget/nzbget> -O

The install script needs to update the path :-)

**Comment by TommyE123** [comment]
Sorry about that. I'd accidently removed the lines which update the systemd file. Ive just reversed the changes so should be ok now if u do another install.

Let me know if this works as ive done the merge on my phone as im away for the weekend and wont be back till later this afternoon!!

**Comment by thinkbig1979** [comment]
Thanks,  looks like you updated the files for Sonarr, but not for NZBGet though.

**Comment by TommyE123** [comment]
Sorry! Can u check its ok now. As i said im on my phone in a hotel at the moment!

**Comment by thinkbig1979** [comment]
Fixed! Nice job. Thanks!
