### ISSUE TITLE
Feature Request - Deluge

### ISSUE THREAD

**Issue by Jakst** [htpcBeginner/AtoMiC-ToolKit#106]
I found an old ticket (#5) for adding **Deluge** support, but it seems to have been closed without being implemented. It would be a nice addition.

**Comment by TommyE123** [comment]
Hi, Thanks for logging a Feature Request for Deluge. I can only assume it was started and never finished however it looks pretty simple to setup now the scripts are becoming more generic. I'll see what i can do over the next week.

**Comment by TommyE123** [comment]
This has now been added :-). 
It would be really appreciated if anyone can confirm it installs and works OK on their system? 
Thanks
Tom

**Comment by Jakst** [comment]
Seems like its working to me. But this install only includes the web client setup, right? Would  be nice to have the daemon install as well http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient

**Comment by TommyE123** [comment]
Closing as confirmed working and was added a while back now.

**Comment by TommyE123** [comment]
Leave a comment
