### ISSUE TITLE
Potential feature - command line options support

### ISSUE THREAD

**Issue by mgiljum** [htpcBeginner/AtoMiC-ToolKit#119]
I wasn't sure if this is a feature that you'd be interested in, but I've got a stable branch (called "options-support") in my fork here:

https://github.com/mgiljum/AtoMiC-ToolKit/tree/options-support

Details are in the README of that branch. It adds command line options like `--install sonarr` for example. I use this script all the time and having these makes doing things a lot faster than using the GUI every time.

I didn't add a pull request as I wasn't sure if you would want this. If not, I won't be offended at all. If it sounds good, I will do a full writeup in the pull request.

**Comment by mgiljum** [comment]
Sure thing, I'll get that pull request written up sometime today, to the dev branch.

**Comment by TommyE123** [comment]
This has now been pushed up to the master branch. For instructions on how to use this please see the readme.
