### ISSUE TITLE
app-git-stash on clean install fails

### ISSUE THREAD

**Issue by mgiljum** [htpcBeginner/AtoMiC-ToolKit#120]
When doing a clean install of an app that uses git for the download, `inc/app-git-stash.sh` is called to stash the local changes.

If the git configs `user.email` and `user.name` are not set, this script fails and prints the following in stdout:

```
--->Git stashing any local changes made to Lazy Librarian...

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@test-VirtualBox.(none)')
Cannot save the current index state

--->Starting Lazy Librarian...

--->All done. Lazy Librarian installation complete.
For access details, run the Lazy Librarian Access Details utility.
```

This doesn't affect a clean install of the app, but could cause problems for updates.

**Comment by TommyE123** [comment]
This is still an issue. 
However I'm looking to remove this as I don't think anyone will be using it.

**Comment by TommyE123** [comment]
Removed git Stashing
