### ISSUE TITLE
Feature Request - OpenVPN

### ISSUE THREAD

**Issue by rinzler40oz** [htpcBeginner/AtoMiC-ToolKit#126]
Hi! 

I'd like to respectfully request an OpenVPN feature that ties into whatever VPN provider we use - perhaps PIA initially for simplicity. It'd be even cooler if this somehow tied into whatever torrent client we use so that P2P traffic could be encrypted. Thanks!

**** UPDATE From Tom ****
- [X] Added [OpenVPN](https://openvpn.net)  
- [X] Added [Private Internet Access VPN DESKTOP Client](https://www.privateinternetaccess.com/pages/downloads)
- [ ] TODO [Private Internet Access VPN HEADLESS Client](https://www.privateinternetaccess.com)

**Comment by TommyE123** [comment]
Thanks for the request.

I think this would be a good idea and would certainly go with PIA to start with.
Let me see what we can do but this could take a bit of time due to its complexity of getting everything working.

Tom

**Comment by rinzler40oz** [comment]
Thanks Tom! 

Here's a manual guide I've been following if it helps as a resource: 

http://www.htpcguides.com/force-torrent-traffic-vpn-split-tunnel-debian-8-ubuntu-16-04/

(It would help long-term to include r/rutorrent as well) :)

**Comment by TommyE123** [comment]
Hi, 

I've now moved the feature requests over to [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit)

I've added OPENVPN and the basic client install for PIA but need to next get the headless working.

Could you please vote for this there so we can start getting a feel for what people would like to be worked on next.

Thanks
