### ISSUE TITLE
sabnzbd not installing on fresh install of ubuntu 16.10

### ISSUE THREAD

**Issue by shipser** [htpcBeginner/AtoMiC-ToolKit#135]
after running the toolkit for sabnzbd+, i get an error: 
"sed: can't read /usr/share/sabnzbdplus/sabnzbdplus.ini: No such file or directory
Modifying host =  in /usr/share/sabnzbdplus/sabnzbdplus.ini file failed."
and sabnzbd does not start.
fresh install of ubuntu server 16.10 on virtualbox vm with 2gb of ram, 8gb vdi hdd and bridged network.

**Comment by TommyE123** [comment]
Thanks for logging an issue. 

I will check this out and see if I can see anything wrong. I've just pushed up a lot of fixes so might be worth just checking this again and seeing if its still an issue.

Thanks
Tom

**Comment by TommyE123** [comment]
Ok its broken on my setup as well. I'll investigate.

**Comment by shipser** [comment]
thank's for the fast response.
installed sabnzbd manually for the time being

**Comment by TommyE123** [comment]
This should now be fixed. :-) I also took the opportunity to do some cleaning up of the scripts in this area. I think there could be still some issues on older distros but this should be fixed for the vast majority of users and only affects the pip installs of a couple of dependencies. I'll work on that over the next few days but wanted to get the main fix out first.

**Comment by shipser** [comment]
thank you, will set up a new vm to test it again

**Comment by TommyE123** [comment]
That would be fantastic! 
I've done some basic testing on Mint 18.1, Raspbian Jessie and Mint 17.3. Its really just me doing all the dev at the moment and this is obviously just an unpaid hobby I have to juggle round my normal day job!
Could you check it creates the download folders in your users home/Downloads folder correctly?
Also if you had any time to test any other apps are still working ok that would be amazing! :-)

**Comment by shipser** [comment]
i'll try to get to that in a few hours

**Comment by shipser** [comment]
it works great now, thank's

**Comment by TommyE123** [comment]
Thanks for letting me know. I'll close this off now.

**Comment by Landelor** [comment]
Sorry to post on a closed issue. But I have this exact problem. Tried a fresh install today.
Ubuntu 17.04

**Comment by TommyE123** [comment]
No problem at all.

I'll have a look this weekend and get back to you. I assume you have got the latest version of the toolkit?

Tom

**Comment by Landelor** [comment]
Yes. Did a git clone and updated from the maintenance section.
Thanks for your effort.

**Comment by TommyE123** [comment]
Please can you give this another try now i've pushed a fix up and let me know how you get on?
Thanks.
Tom

**Comment by Landelor** [comment]
Ran the install again and looks like it's working now.

**Comment by sam1am** [comment]
Just tried this on a fresh Ubuntu Server 16.04.2 install. I am getting the same error.  

`--->Searching for possible port numbers...
Default port: 8080 found in AtoMiC Toolkit config.
grep: /usr/share/sabnzbdplus/sabnzbdplus.ini: No such file or directory
grep: /usr/share/sabnzbdplus/sabnzbdplus.ini: No such file or directory
grep: /usr/share/sabnzbdplus/sabnzbdplus.ini: No such file or directory`
