### ISSUE TITLE
Feature request - Muximux

### ISSUE THREAD

**Issue by shipser** [htpcBeginner/AtoMiC-ToolKit#138]
would like to see https://github.com/mescon/Muximux as one of the options.

**Comment by TommyE123** [comment]
Just a quick update to say progress on this application is coming along nicely with an estimated ETA of the end of the week baring any issues in testing.

**Comment by TommyE123** [comment]
This has now been added. Please could you give it a test and report back with what linux version you used and how you get on :-)

**Comment by TommyE123** [comment]
Closing as has been available for over 2 weeks now with no reported issues.
