### ISSUE TITLE
Feature Request - Cron Job to update applications

### ISSUE THREAD

**Issue by blackley** [htpcBeginner/AtoMiC-ToolKit#147]
@TommyE123 
Is it possible to implement a cron job that will automatically check for updates to atomic-toolkit and perhaps the tools that are installed?

**Comment by TommyE123** [comment]
Hi, Sorry I've not got around to adding this yet. 

I've now moved the feature requests over to [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit)

Could you please vote for this there so we can start getting a feel for what people would like to be worked on next.

Thanks
