### ISSUE TITLE
radarr problem 

### ISSUE THREAD

**Issue by estimadarocha** [htpcBeginner/AtoMiC-ToolKit#148]
--->Downloading and extracting files...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   615    0   615    0     0    708      0 --:--:-- --:--:-- --:--:--   708
  0 8014k    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
gzip: stdin: not in gzip format
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
  0 8014k    0 68127    0     0  31079      0  0:04:24  0:00:02  0:04:22  175k
curl: (23) Failed writing body (1481 != 16360)

is this normal?

**Comment by TommyE123** [comment]
Hi, Thanks for bringing this to my attention. 
It's become broken somehow so i'll get straight on it and see whats happened.

Tom

**Comment by TommyE123** [comment]
Ok, I''ve found the issue and fixed it in the latest commit. https://github.com/htpcBeginner/AtoMiC-ToolKit/commit/a7d24bb37377c46706e2db17013c8da66fe08452 
Can you try it again for me and let me know if it works? I'd be interested to know what linux version you tried it on as well if thats ok?!

thanks
Tom

**Comment by estimadarocha** [comment]
Ubuntu 16.04.2 i will try it later...ok?

**Comment by TommyE123** [comment]
no problem at all. I tried it on Linux Mint 18.1 and it now seems to work fine again.

Thanks again for letting me know this was broken.

**Comment by estimadarocha** [comment]
fixed thanks!

**Comment by TommyE123** [comment]
Thanks again for logging the issue.
Tom
