### ISSUE TITLE
Madsonic needs login details

### ISSUE THREAD

**Issue by thagoat** [htpcBeginner/AtoMiC-ToolKit#149]
There seems to be no user set upon installation. Also the default admin:admin do not work. And when accessing the app details it provides only "Cannot determine or user name not set" and "Not displayed for security"

**Comment by TommyE123** [comment]
Hi thanks for logging an issue,

I'll check this out later tonight as I'm not sure what this could be off the top of my head. As far as im aware the default password should be admin:admin as you mentioned. Unfortunately the access details page needs some work to better support the growing number of applications. Madsonic doesn't currently display any password details.

Things to try\check, a bit obvious I know but I felt I should ask!
1. Make sure your not putting in any uppercase letters in the username\password boxes.
2. Give your PC a reboot!
3. You are using the latest version of the Toolkit and your Linux packages are up to date.
4. Have you tried to install Subsonic as well? If so remove both apps reboot and reinstall Madsonic.
5. Remove and reinstall Madsonic?

Could you let me know what Linux distro and version you are using?

Thanks
Tom

**Comment by thagoat** [comment]
Thanks for the quick answer Tom!
Yeah I've covered the checklist you gave, and no dice. I did not install Subsonic, so probably not the issue, I'm guessing. I poked around the config files but I didn't edit anything.
The script is running on Ubuntu Server 16.10, which is updated daily. 
Good hunting!
Shawn

**Comment by TommyE123** [comment]
Hi Shawn,

So i've installed this on various different distros\versions of VM's including Ubuntu Desktop 16.10 and none of them have this issue!?! I've just noticed you said you had Server installed but I can't see it making much difference. (famous last words!)

1. Has it ever worked?
2. I would remove (deleting folders), reboot, reinstall. reboot, try!
3. Can you try another browser just incase you have a cached password?
4. Might be worth looking on the madsonic forums to see if anyone else has this issue?

Else i'm at a slight loss at the minute :-(

**Comment by thagoat** [comment]
Tom,
I reinstalled a few days ago after I noticed a PR and everything is working correctly now. Not sure if it was a code change or something weird on my server. But it's all good now, and I'm enjoying madsonic! Thanks for looking into it =)
