### ISSUE TITLE
Never goes to software select screen.

### ISSUE THREAD

**Issue by werethless12** [htpcBeginner/AtoMiC-ToolKit#150]
I run the setup.sh under a user with sudo rights, and it asks for me to type in the username, which I do, and then I'm taken to the "Thank you for using the AtoMiC Toolkit"

**Comment by TommyE123** [comment]
Hi, thanks for logging an issue.
I'm sure we can get this working, can you answer the questions below?

1. Has it ever worked?!
2. What directory did you clone the script into? Does it have any spaces?
3. Within the directory you cloned to, does 'sudo bash setup.sh' work?
4. What Linux distribution and version are you running?

Thanks
Tom

**Comment by werethless12** [comment]
1, It has only ever gotten me to the user select screen
2. My users home folder, no spaces
3. Yes, but it doesn't let me install anything
4. Debian 8.7

**Comment by TommyE123** [comment]
Hi again, thanks for the answers.

So I created a brand new Debian 8.7.1 VM and installed git.
Added myself using 'visudo' 'tom ALL=(ALL:ALL) ALL'.
I then cloned to /tom/AtoMiC-ToolKit.
Ran 'sudo bash setup.sh' and after accepting and entering my name was presented with the software install menu. I then proceeded to test installing some apps.

I've not come across this issue before. For a good while now i've been cloning into /opt/AtoMiC-ToolKit and then running the 'sudo bash atk-installer.sh' which then allows a simple 'sudo atk' to return straight to the menu from wherever you are in the terminal. Over the coming weeks i'm going to change the install instructions to match my setup.

Could you try removing the AtoMiC-ToolKit folder completely and try re-pulling it down? 

Is anyone else having this issue?

Tom

**Comment by DennisFederico** [comment]
I'm also having the issue, using Debian 8 and a Pine64 (ARM 64) device

**Comment by DennisFederico** [comment]
Is there any kind of log that I can check?

**Comment by TommyE123** [comment]
Thanks for the feedback. 
So it appears it could be Debian related. I've made a few changes to the setup file but they are extremely minor so not holding out much hope it will fix it yet.

When it goes to the thank you message. Are you able to scroll back up the terminal window and see if theres any other messages?

Do you have a /AtoMiC-ToolKit/tmp/userinfo file with your username and group in it?

**Comment by DennisFederico** [comment]
Hi Tommy, I'll test the change this weekend, I'll confirm if I can scroll back up before pulling the changes.

Thanks mate.

**Comment by TommyE123** [comment]
Has anyone still got this issue? 

I've been unable to replicate this and would really appreciate it if someone could give me steps to reproduce this issue.

Thanks

**Comment by DennisFederico** [comment]
Hi there,
I'm not able to test the issue anymore, I've repurposed the ARM64 device
and using and Intel+Ubuntu now, the toolkit is working very good there

Best Regards

**Comment by PeteB1983** [comment]
Im having this issue, truing to set up on a qnap 853A in a docker, I have tried https://hub.docker.com/_/debian/
and https://hub.docker.com/_/ubuntu/
both seem to install and run but i cant get the gui to run, I have given in and have managed to install the  packages from the cli, but Im still interested in getting it running!

**Comment by TommyE123** [comment]
Hi @PeteB1983,

Thanks for letting me know this is still an issue. I would love to get to the bottom of this one if I can. Is there any chance you could contact me on [Gitter](https://gitter.im/Tommye123) and we could have a quick look at whats going on?

Thanks
Tom

**Comment by PeteB1983** [comment]
@TommyE123 sure, I just logged in
