### ISSUE TITLE
Installing Plex could automatically enable repository updating

### ISSUE THREAD

**Issue by nemchik** [htpcBeginner/AtoMiC-ToolKit#152]
When Atomic installs Plex it would be nice if it would automatically enable repository updates per this article:
https://support.plex.tv/hc/en-us/articles/235974187-Enable-repository-updating-for-supported-Linux-server-distributions
Or possibly present the option to do this so that people can opt in/out.

**Comment by TommyE123** [comment]
Hi, thanks for logging this. 

I just looked at the article you linked to and we are already using that repository to install Plex for all Ubuntu\Debian versions :-) We also use dev2day for Arm devices and Ninthgate for Old Wheezy versions.

That means if u periodically in the ToolKit use the Maintenance\Update Linux. You will automatically pickup any new updates from those repositories. In the future I am looking to offer to add an option to create a cron job to automate this process.

Does this answer your request ok?

Tom

**Comment by nemchik** [comment]
I'm glad to know that Atomic gets plex from this repository, but the purpose of my request is more so that I can logon to my box, run `apt update & apt upgrade` and call it a day. While the idea of cron jobs is interesting and certainly going to be valuable to some, I prefer to manually do my updates (gives me a bit of control and comfort), but I like them to all be done with one update method (the above mentioned command) wherever possible.

**Comment by TommyE123** [comment]
You can do exactly that command now which will pickup any updates for Plex. That is also pretty much what the Update Linux does in the toolkit but with a few cleanups as well :-)
