### ISSUE TITLE
Sonarr installs with root user

### ISSUE THREAD

**Issue by Jakst** [htpcBeginner/AtoMiC-ToolKit#159]
On my Ubuntu 17.04 machine, Sonarr install into /opt/NzbDrone with root user, causing Sonarr to complain. No other product that I have installed through atomic has this problem.

**Comment by TommyE123** [comment]
Thanks for bring this to my attention. 
I've fixed this in my branch and will push the changes up when I've finished a few other apps I'm working on.

[![Join the chat at https://gitter.im/htpcBeginner/AtoMiC-ToolKit](https://badges.gitter.im/htpcBeginner/AtoMiC-ToolKit.svg)](https://gitter.im/htpcBeginner/AtoMiC-ToolKit?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
Tom

**Comment by TommyE123** [comment]
I think this should now be resolved. Although I've tried to test the changes can someone give it a try and confirm its ok now?

Thanks
Tom

**Comment by TommyE123** [comment]
Closing this as I believe this has now been fixed and i've not heard of any further issues.
Closing as has now been added and not heard of any issues.
