### ISSUE TITLE
Grammar error?

### ISSUE THREAD

**Issue by sigboe** [htpcBeginner/AtoMiC-ToolKit#16]
The script tells me

    NOTE: At this point, this script has been confirmed to work only on Ubuntu variants.

while the readme.md tells me

    May work on other distributions but that has not been tested.

So I am wondering if the note in the script should actually say `this script has only been confirmed to work on Ubuntu variants.` which means something entirely different that the current text. If you did not notice it, I moved the word `only` and the meaning now means its only been tested on Ubuntu variants, while the previous meaning means that its been tested to only work on Ubuntu variants.

I am only opening this Issue because its good to be clear in meaning.

**Comment by htpcBeginner** [comment]
Good point. Thanks!

**Comment by htpcBeginner** [comment]
Fixed in dev branch.
