### ISSUE TITLE
Add Organizr as install option

### ISSUE THREAD

**Issue by duffkiligan** [htpcBeginner/AtoMiC-ToolKit#163]
I just discovered Organizr, a (somewhat) new HTPC Managing interface in the same vein as Muximux but PHP based and with more features built-in
Plex Authentication, user management (groups coming), color schemes, customization, etc

Seems like a new up and coming project that can really benefit the users of Atomic Toolkit with multiple services installed.

https://github.com/causefx/Organizr

(I am not affiliated with organizr in anyway, I just really like it and I love the atomic toolkit)

**Comment by TommyE123** [comment]
Thanks for bringing this to my attention. 

I'm open to adding anything people would like so I'll certainly look into this.

Tom

**Comment by TommyE123** [comment]
This has now been added. :-)
If anyone wants to confirm its working ok that would be really helpful.

[![Join the chat at https://gitter.im/htpcBeginner/AtoMiC-ToolKit](https://badges.gitter.im/htpcBeginner/AtoMiC-ToolKit.svg)](https://gitter.im/htpcBeginner/AtoMiC-ToolKit?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Tom

**Comment by TommyE123** [comment]
Closing as has now been added and not heard of any issues.
