### ISSUE TITLE
Port to FreeBSD

### ISSUE THREAD

**Issue by mrowlinson** [htpcBeginner/AtoMiC-ToolKit#165]
I'm seeing more and more people using FreeBSD as their home servers, especially with the popularity of FreeNAS. I've been thinking about giving it a try and switching from Ubuntu to FreeBSD if I like it. I would love it to see this toolkit ported to FreeBSD. It would make it so much easier if I could use the toolkit to back up my settings for all my applications and copy them over to FreeBSD to minimize downtime.

**Comment by shortbus** [comment]
yes, please port

**Comment by TommyE123** [comment]
Hi, 
This isn't going to be an easy task to port this over to FreeBSD however I don't mind keeping this open to see if we can do this in future.

I've now moved the feature requests over to [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit)

Could you please vote for this there so we can start getting a feel for what people would like to be worked on next.

Thanks
