### ISSUE TITLE
Feature Request - Add rclone support

### ISSUE THREAD

**Issue by hjtech** [htpcBeginner/AtoMiC-ToolKit#166]
Though it is easy to install, it would be great to have it as an option, possible?

**Comment by TommyE123** [comment]
Yep shouldn't be a problem. thanks for the suggestion.

**Comment by TommyE123** [comment]
Hi, Sorry I've not got around to adding this yet. 

I've now moved the feature requests over to [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit)

Could you please vote for this there so we can start getting a feel for what people would like to be worked on next.

Thanks
