### ISSUE TITLE
Installs ruTorrent in wrong directory

### ISSUE THREAD

**Issue by 2wenty2wo** [htpcBeginner/AtoMiC-ToolKit#172]
When installing ruTorrent with ATK it places the folder in **/var/www** when by default the root directory is **/var/www/html**.

I modified my apache2 config to look at **/var/www** and it works but if people don't do this themselves your installer doesn't work "out of the box".

Regards

**Comment by TommyE123** [comment]
Hi,
Sorry I've not got back to you sooner.

I decided rightly or wrongly to go with **nginx** as the http server to use with this so it doesn't change the apache config and uses a custom **/etc/nginx/sites-available/AtoMiC-ToolKit-configured-sites** file to manage applications the toolkit installs. It should also disable the apache service on startup.

I didn't have any plans to change or add support for apache however i'm completely open to ideas how we can make it more compatible with both which won't break existing\future installs of applications. If you can help with this please don't hesitate to discuse on Gitter https://gitter.im/htpcBeginner/AtoMiC-ToolKit

Hope this makes sense I'm certainly no expert in this area!!

Tom

**Comment by TommyE123** [comment]
I'm closing this as i don't think there is anything that needs changing as I explained above.
