### ISSUE TITLE
Hydra service doesn't work anymore

### ISSUE THREAD

**Issue by nemchik** [htpcBeginner/AtoMiC-ToolKit#173]
https://github.com/theotherp/nzbhydra/commit/6cca2685ff6c9fbd03d7498490411aac84fa78b3

This seems to have broken Atomic's ability to install NZB Hydra service.

**Comment by cadeon** [comment]
Issue is with /etc/systemd/system/nzbhydra.service - paths in there are example paths. 

ExecStart=/usr/bin/python2 /opt/nzbhydra/nzbhydra/nzbhydra.py --nobrowser

was the fix for me.

**Comment by cadeon** [comment]
I got mine working with: 
`[Unit]
Description=NZBHydra Daemon
Documentation=https://github.com/theotherp/nzbhydra
After=network.target

[Service]
User=media
Group=media
Type=simple

# NZBHydra requires python > 2.7.9 *and* < 3.x. Most distributions offer both,
# often `python` is 3.x and 2.x is `python2` or `python2.7`. Use --version
# to figure out which is correct and `which python` to find the full path to
# correct the line below.

# NZBHydra stores it's configuration file and database in the home directory
# of the user account it runs as. Add the below options to change its behavior
# --config /path-to/settings.cfg --database /path-to/nzbhydra.db
ExecStart=/usr/bin/python /opt/nzbhydra/nzbhydra.py --daemon --nobrowser

# In Settings, enable "Shutdown to restart" so NZBHydra will just shut down and
# let systemd restart it. To actually shut down, NZBHydra will exit with a
# status of 6, signaling systemd not to restart it.
Restart=on-failure
SuccessExitStatus=6
RestartPreventExitStatus=6

[Install]
WantedBy=multi-user.target
`

**Comment by TommyE123** [comment]
Can anyone commit a fix for this? I can push a fix up now but won't be able to look at this myself for a while as I'm at a wedding in Greece :-)

**Comment by nemchik** [comment]
https://github.com/nemchik/AtoMiC-ToolKit/commit/49e73e521786591e7133d0b8437f860026c29f7a this seems to work to fix it, but it does not include some of the things that were previously being defined such as the pid file, config file, and database. I think they end up in the same place when not defined, but there may have been a reason for having them defined like they were that i am unaware of?

**Comment by blackley** [comment]
I have python 2.7.13 running as my default version and it works correctly with NZBHydra.  I am also running this script that I then launch from systemd.  Try this and report back…

 

/opt/nzbhydra/Nzbhydrad

--Start File

#!/bin/bash

appName="nzbhydra"

pidFile="/var/run/$appName.pid"

case $1 in

 

    start)

    #echo $$ > $pidFile;

    exec 2>&1 /usr/bin/python /opt/nzbhydra/nzbhydra.py --daemon --nobrowser --pidfile /var/run/$appName.pid --config /opt/nzbhydra/nzbhydra.cfg --database /opt/nzbhydra/nzbhydra.db

    ;;

 

    stop)

      if [[ -f "$pidFile" ]]; then

        PID=$(< "$pidFile")

        pkill -F $PID 2> /dev/null

        rm "$pidFile"    

      fi

    ;;

 

    *)

    echo "usage: $appName {start|stop}"

    ;;

 

esac

 

exit 0

--end file

 

 

/etc/systemd/system/nzbhydra.service

---start file

 

[Unit]

Description=NZBHydra Daemon

Documentation=https://github.com/theotherp/nzbhydra

Requires=network.target

After=network.target

 

[Service]

Type=forking

ExecStart=/opt/nzbhydra/nzbhydrad start

ExecStop=/opt/nzbhydra/nzbhydrad stop

User=root

Group=root

Restart=always

RestartSec=5

StartLimitInterval=60s

StartLimitBurst=3

 

[Install]

WantedBy=multi-user.target

--end file

**Comment by TommyE123** [comment]
I've taken a VERY quick look at this and @nemchik is correct that the service file has been rewritten which has broken our install. If you previously installed it you should be fine though. If you can just bear with me till I get back in a few days time so I can then test the fix and push it up.

Thanks
Tom

**Comment by nemchik** [comment]
If this https://github.com/nemchik/AtoMiC-ToolKit/commit/49e73e521786591e7133d0b8437f860026c29f7a does the trick and has everything needed I can make a PR, I just didn't yet because I wasn't sure if the things that were removed needed to be added back in for some reason.

**Comment by TommyE123** [comment]
This should now be fixed and working again. :-) @nemchik Thanks for bring this to our attention. I ended up leaving the extra parameters as they were as the current scripts push them to /opt/nzbhydra rather than the home directory of the user account. The backup scripts also look for them there and at the moment I'd rather leave them alone and just get it working again!
