### ISSUE TITLE
Change masonic port?

### ISSUE THREAD

**Issue by karl0ss** [htpcBeginner/AtoMiC-ToolKit#174]
For starts, great work on the script, really makes reinstall so much easier...

But I'm struggling to work out to change the masonic port, I have even changed the port in the args line, but it just sticks at 4040...any idea?

Thanks

**Comment by blackley** [comment]
Please see the masonic support forum link here for details on where to change the port - http://forum.madsonic.org/viewtopic.php?f=14&t=1106&p=3373&hilit=change+port+4040#p3398

**Comment by karl0ss** [comment]
That worked, thank you.
