### ISSUE TITLE
Plex fails to install

### ISSUE THREAD

**Issue by karl0ss** [htpcBeginner/AtoMiC-ToolKit#175]
Plex doesn't seem to install with the latest version of the script, just fails to install...

Anyone have any idea?

**Comment by TommyE123** [comment]
This looks to have broken while i've been away probably due to the new Plex version releases over the past few weeks.
I'll take a look into it.

Thanks for letting us know.
Tom

**Comment by karl0ss** [comment]
I have just tried it, without any update to you script, and this is now working again..unless your script auto updated.

Great work mate
