### ISSUE TITLE
Feature Request - Add nZEDb

### ISSUE THREAD

**Issue by nemchik** [htpcBeginner/AtoMiC-ToolKit#177]
https://github.com/nZEDb/nZEDb/

This would be really handy!

**Comment by TommyE123** [comment]
Hi, Thanks for the suggestion. 

I've now moved the feature requests over to [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit)
Could you please vote for this there so we can start getting a feel for what people would like to be worked on next.

Thanks
