### ISSUE TITLE
plex error

### ISSUE THREAD

**Issue by estimadarocha** [htpcBeginner/AtoMiC-ToolKit#185]
Ficheiro de configuração '/etc/apt/sources.list.d/plexmediaserver.list'
 ==> Ficheiro no sistema criado por si ou por um script.
 ==> Ficheiro também no pacote disponibilizado pelo maintainer do pacote.
   O que deseja fazer? As suas opções são:
    Y ou I  : instalar a versão do pacote do maintainer
    N ou O  : manter a versão actualmente instalada
      D     : mostrar diferenças entre as versões
      Z     : iniciar uma shell para examinar a situação
 A acção padrão é manter a sua versão actual.
*** plexmediaserver.list (Y/I/N/O/D/Z) [padrão=N] ? y
A instalar nova versão do ficheiro de configuração /etc/apt/sources.list.d/plexmediaserver.list ...
Created symlink /etc/systemd/system/multi-user.target.wants/plexmediaserver.service → /lib/systemd/system/plexmediaserver.service.
Job for plexmediaserver.service failed because the control process exited with error code.
See "systemctl status plexmediaserver.service" and "journalctl -xe" for details.
dpkg: erro ao processar o pacote plexmediaserver (--configure):
 subprocesso script post-installation instalado retornou erro do status de saída 1
A processar 'triggers' para ureadahead (0.100.0-19) ...
Foram encontrados erros enquanto processava:
 plexmediaserver
E: Sub-process /usr/bin/dpkg returned an error code (1)

any ideas?

**Comment by TommyE123** [comment]
There's various issues with the plex installer at the moment that i'm trying to fix. 
Hang on and i'll try and get a fix out as soon as I can over the next few days.

**Comment by TommyE123** [comment]
Hi,

I’ve pushed up some changes that I hope has fixed this and would be grateful if you could give it another try and report back with your results?

Thanks
Tom

**Comment by kunallanjewar** [comment]
Plex install is now working for me after recent pull.

**Comment by TommyE123** [comment]
Thanks for letting me know its working for you. I really appreciate the feedback.
I'll leave these issues open for a few more days so anyone can just confirm its now working for them.

Tom

**Comment by estimadarocha** [comment]
fixed thanks! sorry for delay!
