### ISSUE TITLE
Radarr does not restore nzbdrone.db

### ISSUE THREAD

**Issue by kunallanjewar** [htpcBeginner/AtoMiC-ToolKit#190]
This is true for both Sonarr and Radarr. To restore we need to put back config.xml and nzbdrone.db
But toolkit only restores config.xml.

**Comment by TommyE123** [comment]
Thanks for letting me know. 
If anyone fancies adding a pull request and adding it feel free. Or I'll try and get round to this when I can.

Tom

**Comment by TommyE123** [comment]
Sorry I should have closed this off last month when i applied the fixes but somehow missed this.
Everything should be backing up and restoring correctly now.
