### ISSUE TITLE
Problem with Nginx

### ISSUE THREAD

**Issue by Arck0s** [htpcBeginner/AtoMiC-ToolKit#191]
Hello,
I install the script on my new Debian 8 server to test, Radarr and Sonarr no worries; RTorrent idem, everything goes well, but to rutorrent it blocks:

```
AtoMiC Nginx Installer Script

--->Stopping apache2...
Nothing found to stop

--->Disabling apache2...
/etc/init.d/apache2 Disabled
insserv: warning: current start runlevel(s) (empty) of script `apache2' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `apache2' overrides LSB defaults (0 1 6).

--->Stopping Nginx...
Nothing found to stop

--->Adding Nginx repository...
deb http://nginx.org/packages/debian/ jessie nginx
deb-src http://nginx.org/packages/debian/ jessie nginx

--->Adding Nginx Keys...
OK

--->Refreshing packages list...
Done

--->Installing Nginx...
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Les NOUVEAUX paquets suivants seront installés :
  nginx
0 mis à jour, 1 nouvellement installés, 0 à enlever et 1 non mis à jour.
Il est nécessaire de prendre 784 ko dans les archives.
Après cette opération, 2 889 ko d'espace disque supplémentaires seront utilisés.
Réception de : 1 http://nginx.org/packages/debian/ jessie/nginx nginx amd64 1.12.1-1~jessie [784 kB]
784 ko réceptionnés en 0s (8 490 ko/s)
Sélection du paquet nginx précédemment désélectionné.
(Lecture de la base de données... 46045 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../nginx_1.12.1-1~jessie_amd64.deb ...
----------------------------------------------------------------------

Thanks for using nginx!

Please find the official documentation for nginx here:
* http://nginx.org/en/docs/

Please subscribe to nginx-announce mailing list to get
the most important news about nginx:
* http://nginx.org/en/support.html

Commercial subscriptions for nginx are available on:
* http://nginx.com/products/

----------------------------------------------------------------------
Dépaquetage de nginx (1.12.1-1~jessie) ...
Traitement des actions différées (« triggers ») pour man-db (2.7.0.2-5) ...
Traitement des actions différées (« triggers ») pour systemd (215-17+deb8u7) ...
Paramétrage de nginx (1.12.1-1~jessie) ...
Traitement des actions différées (« triggers ») pour systemd (215-17+deb8u7) ...

--->configuring NGINX 
Set the correct folder permissions
cp: impossible de créer le fichier standard « /etc/nginx/sites-available/AtoMiC-ToolKit-configured-sites »: Aucun fichier ou dossier de ce type
\e[91mCould not move AtoMiC-ToolKit-configured-sites file.\033[0m

```
Any idea ?
Thank

**Comment by Arck0s** [comment]
I have the same text whan I try to install organizr
```
--->configuring NGINX 
Set the correct folder permissions
cp: impossible de créer le fichier standard « /etc/nginx/sites-available/AtoMiC-ToolKit-configured-sites »: Aucun fichier ou dossier de ce type
\e[91mCould not move AtoMiC-ToolKit-configured-sites file.\033[0m
```

**Comment by Arck0s** [comment]
I have just tried with many applications, the last one is Muximux, and all those that touch Nginx have the same error. They do not manage to modify Nginx therefore its plant.

**Comment by TommyE123** [comment]
Hi, Thanks for reporting this. I will take a look.

**Comment by Arck0s** [comment]
Thank you

**Comment by bonyboy** [comment]
I had the same trouble as @Arck0s and how I fixed it was went into /etc/nginx/sites-enabled/AtoMiC-ToolKit-configured-sites and added my WAN ip after 0.0.0.0.

Hope this helps.

**Comment by TommyE123** [comment]
The error suggests it cant copy `AtoMiC-ToolKit-configured-sites` to the `/etc/nginx/sites-enabled/` folder. I'm suspecting its a permissions issue. I'm just creating a Debian 8.9 VM and hope I might be able to get to the bottom of this.

I think @bonyboy answer would help if you wanted to access the application externally however as the file isnt there in the first place I doubt it will help much at the moment?

I've not forgotton about this issue. Hold tight and we'll fix it don't worry :-)
Tom

**Comment by TommyE123** [comment]
I've applied some Nginx fixes. 
Not sure if its related but can you give it another try?

thanks
Tom

**Comment by kesurof** [comment]
Hello, I have exactly the same problem, I did the installation today.
Do you have a solution?

**Comment by TommyE123** [comment]
I'm currently rewriting the Nginx install to use the official mainstream repositories with some bug fixes as well. I'm just in the final stages of testing and hope to push the changes up later this evening.

Thanks for letting me know.
Tom

**Comment by kesurof** [comment]
Hi Tom, thanks for the response as fast, good luck and thanks for all this work.

**Comment by TommyE123** [comment]
I've pushed up fixes that I hope should resolve this. Can you report back how you get on? Thanks

**Comment by kesurof** [comment]
I did the installation this morning of Nginx, no problem, no error, it works very well, thanks

**Comment by TommyE123** [comment]
That's great news!
@Arck0s Have you had a chance to retry this install?
Thanks

**Comment by Arck0s** [comment]
Hello. 
Sorry, I'm on the move for my job.
Normally I could try this weekend.
Thank you

**Comment by TommyE123** [comment]
No problem at all. 
Just let me know how you get on and I'll help where I can.

**Comment by Arck0s** [comment]
Hello,

I test on VM Scalawag on Debian Jessy Up to date, but I've a problem for installation

`│││││││││ ├─┤ │ ├─┘│  ├┴┐├┤ │ ┬│││││││├┤ ├┬┘ │  │ ││││
 └┴┘└┴┘└┴┘o┴ ┴ ┴ ┴  └─┘└─┘└─┘└─┘┴┘└┘┘└┘└─┘┴└─o└─┘└─┘┴ ┴
                __  ___             
  /\ |_ _ |\/|./     | _  _ ||_/.|_ 
 /--\|_(_)|  ||\__   |(_)(_)|| \||_ 

--->DISCLAIMERS:
Already agreed. Can be cleared in the next screen.

--->USER INFORMATION:
--->Type the username of the user you want to use for managing apps and press [ENTER]...
Typically, this is your system login name (IMPORTANT! Ensure correct spelling and case). Do not use "root". Current username is "": arck0s

Invalid username. No changes were made. Please rerun script and provide correct username.

root@scw-******:/opt/AtoMiC-ToolKit# 


`
Any idea ?

**Comment by TommyE123** [comment]
Hi,

The error appears because it checks to see if there is a directory called `/home/XXXX`. `XXXX` being whatever you typed in as your username. With a quick google I assume you mean your using [Scaleway](https://www.scaleway.com/)? 

Looking at the next bit of the error it suggests your home directory is `scw-******`
I don't have any experience using Scaleway i'm afraid but from what you've posted it suggests it creates your home directory with `scw-` in front of the username you selected?

You could try putting `scw-` in front of your username when you type it in but i'm not sure of the knock on effects later on. 

If this doesnt work are you able to select what the home directory name is called or did you somehow choose `scw-******`

I could possibly make a change to the toolkit to try and workout what the home directory is based on what username you typed in. However this would take some time to implement and I'm not sure how common it is to have a different folder name to the username and if that's even possible?!

Hope this helps
Tom

**Comment by Arck0s** [comment]
Hi,

I try with scw-****** but it’s doesn’t works. 
So I try on my Mac with Debian VM. Installation it’s okay but I’ ve somme difficulty for local connexion but this is another story :)
Thanx for tour great job 👍🏼
