### ISSUE TITLE
Sonarr install broken

### ISSUE THREAD

**Issue by kunallanjewar** [htpcBeginner/AtoMiC-ToolKit#196]
--->Mono installation complete.

--->Installing Sonarr...
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nzbdrone

**Comment by TommyE123** [comment]
This looks like it possibly didn't add the repository correctly. 
Can you see if you got any other errors before this one?
What Linux version are you running?

Thanks
Tom

**Comment by TommyE123** [comment]
Closing due to not being able to reproduce the issue, not enough information given and has been outstanding for a month. If you are still having trouble please create a new issue and fill out the Issue template.

Thanks
