### ISSUE TITLE
HTPC Manager and qBittorrent install on port 8085

### ISSUE THREAD

**Issue by BlakeDarwinXE** [htpcBeginner/AtoMiC-ToolKit#2]
I was testing out installing and removing different apps with your tool and notice that HTPC Manager and qBittorrent both install on port 8085. 

qbittorrent-installer.sh Line 117
sudo sed -i 's/XXXX/8085/g' /etc/init.d/qbittorrent-nox-daemon || { echo -e $RED'Replacing port in default failed.'$ENDCOLOR ; exit 1; }

**Comment by htpcBeginner** [comment]
Fixed.
