### ISSUE TITLE
[request] windows version of AtoMiC Toolkit?

### ISSUE THREAD

**Issue by JourneyOver** [htpcBeginner/AtoMiC-ToolKit#20]
Do you think it would be possible if you could make a windows version of this possibly? I don't mind if you can't or don't want to, just would love to use this for easy installation but I don't use Linux/Ubuntu or any other variants.

**Comment by htpcBeginner** [comment]
Unfortunately, I do not plan to: mainly because I don't know to much about how to port this to Windows.
