### ISSUE TITLE
rutorrent install broken ubuntu 16.04.3 fresh install

### ISSUE THREAD

**Issue by kablam** [htpcBeginner/AtoMiC-ToolKit#202]
I have been haveing trouble with my rutorrent for a while and decided to reinstall my server so I downloaded the latest ubuntu image (ubuntu-16.04.3-server-amd64.iso) and installed it logged thru ssh downloaded atomic toolkit and installed webmin. Next i installed rtorrent and continued to install rutorrent and got this error message.

https://pastebin.com/anU0ZfAG

any advice or help? i posted my steps here so you  could verify my problem. I received the same error before with my old installation ubuntu 16.04.2 which i had been running for about 6 months  i had rutorrent working and after a update it broke for some reason and i was never able to get it back running again thats why i reinstalled and ran into the same problem

**Comment by TommyE123** [comment]
I've pushed up fixes that I hope should resolve this. Can you report back how you get on? Thanks

**Comment by kablam** [comment]
im happy thx man
