### ISSUE TITLE
instaling etc packages with rutorrent

### ISSUE THREAD

**Issue by Dnkhatri** [htpcBeginner/AtoMiC-ToolKit#210]
## The problem

On installing rutorrent it also installs ffmpeg, unrar, php ngnix etc

- [ ] Linux Mint
)

### I'm not a dummy, so I've checked these!

- [ ] I'm using the latest version of AtoMiC-ToolKit. 
- [ ] All my Linux distro packages are up to date and I don't see any errors while updating. 
- [ ] I've checked there are no current open issues relating to my problem!

**Comment by TommyE123** [comment]
Hi, Thanks for logging an issue. 

All those packages are installed by design as they are dependencies of rutorrent in order for it to work?

Are you having a problem running rutorrent or feel it's installing something that's not needed?

Thanks
Tom

**Comment by Dnkhatri** [comment]
I was trying out different clients rutorrent installed a lot of packages on install but didnt remove them on uninstall so was wondering if something etc is being installed
