### ISSUE TITLE
Updating libtorrent for deluge

### ISSUE THREAD

**Issue by Dnkhatri** [htpcBeginner/AtoMiC-ToolKit#211]
I am not an expert user of linux so have been using this toolkit to install and update most of my htpc software. Tried using the instructions on the deluge website to update the libtorrent version used with torrent to the lastest version. So far was unable to so would like if such an update can be added to atomic tookit

**Comment by TommyE123** [comment]
Hi, Sorry i've not got back to you sooner.

Currently Deluge is installed via the official  Deluge repository for most Linux distributions. This also includes the latest stable version of libtorrent that they recommend using with Deluge. I've noticed that the repository also supports Debian which Atomic-Toolkit should be taking advantage of so I will work on getting that added. If you want to try and get the very latest version of libtorrent then it has to be built from source with different parameters required depending on the hardware etc it was being built for. This would also require manually updating as apposed to automatically updating via the repository.  However quickly looking through the Deluge forums, it appears to be suggesting that your better off sticking with the version available from their repository. 

For those reasons I feel its best to stick with how it currently installs and I will add Debian\Raspbian to use the official repository as well in future.

Hope that explains it but if you want to ask anymore questions then feel free to contact me on [Gitter](https://gitter.im/TommyE123)

thanks 
Tom

**Comment by Dnkhatri** [comment]
Thanks for the detailed explanation. I understand why you would not want to make it the default but I get better upload speeds and am able to connect to more peers by using the latest version of libtorrent. I was able to find an easy way to get the latest version without compiling myself by adding qbittorent unstable ppa and using that to update libtorrent.
https://launchpad.net/~qbittorrent-team

**Comment by TommyE123** [comment]
Hi, 
Sorry I've not got back to you sooner again, but I've been away on a much needed holiday! 

That is a super spot that they use a newer more up to date version in that repo. I'll look at adding this, I'm thinking the best way would be to add the repo separately at the install stage when we add the Deluge repo..

Thanks for your time and investigation work!

Tom
If you want to discuss anything with me please don't hesitate to contact me on [Gitter](http://gitter.im/Tommye123).
Don't forget to vote for new features on [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit) and help drive the focus of [AtoMiC-ToolKit](https://github.com/htpcBeginner/AtoMiC-ToolKit)!
