### ISSUE TITLE
Can't backup Plex with Script

### ISSUE THREAD

**Issue by serdood** [htpcBeginner/AtoMiC-ToolKit#216]
The backup runs but there is no data in the file.  It is not finding the directory due to the spaces between Application Support etc.  as shown below.

--->Backing up files...
tar: Removing leading `/' from member names
tar: /var/lib/plexmediaserver/Library/Application: Cannot stat: No such file or directory
tar: Support/Plex: Cannot stat: No such file or directory
tar: Media: Cannot stat: No such file or directory
tar: Server: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

All files/folders present from the following list were backed up:
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server

--->Moving Plex Media Server backup to /opt/AtoMiC-Toolkit/backups/plexmediaserver_11-10-2017_02-51.tar.gz...

--->All done. Plex Media Server backup complete.

Is there something I need to do?  Running Unbuntu server 16.04.3 fresh installs on 2 computers.  

Is there a way to have the script automatically run periodically to backup plex and plexpy etc?  Newbie here with linux.

thanks

**Comment by TommyE123** [comment]
Hi, Thanks for bringing this to my attention. 

I've fixed the backup issue in my branch last week however I'm on holiday at the moment and am reluctant to push up the changes in case something breaks and I'm not around to fix it!!

Tom

**Comment by TommyE123** [comment]
Hi,

I've fixed the backup paths containing spaces backing up and restoring (I hope!) (Please feel free to reopen this if its still causing you issues)

With regards to the periodic backups I've now moved the feature requests over to [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit)

Could you please vote for this there so we can start getting a feel for what people would like to be worked on next.

Thanks

**Comment by serdood** [comment]
Thanks It is working now.  Is there a way I can edit to skip certain directories to reduce the size of the backup?

**Comment by TommyE123** [comment]
Currently it backs up the whole directory. [list found here](https://github.com/htpcBeginner/AtoMiC-ToolKit/blob/master/plexmediaserver/plexmediaserver-backup-files) (you can edit this to change what it backs up but it will get overwritten if you updated the toolkit) I've not really looked at what exactly should be backed up as its been like that since I started helping out here! If you want to suggest a new set of directories, I'll happily change what its currently backing up if it shouldn't be doing the whole directory!

**Comment by serdood** [comment]
It is good so far.  The only thing I might eliminate is the directory where the synced transcoded media is found to reduce the space.  I believe it is located in /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Cache/ Transcode.  This folder can get pretty big if you allow syncing of media to clients.

**Comment by serdood** [comment]
The Plex is working great now but now Plexpy is not backing up the whole directory anymore.  It is only backing up the config file and the database does not get backed up.  Do I need to edit a file to do the whole directory?

**Comment by TommyE123** [comment]
If you have a sec and dont mind, come and speak to me quickly on [Gitter](https://gitter.im/tommye123) which is just a private chat for github users if that's Ok?

**Comment by serdood** [comment]
sure on right now.
