### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by goodpunk6** [htpcBeginner/AtoMiC-ToolKit#217]
Configure all URLs for nginx at install.

**Comment by nemchik** [comment]
Could you provide more info about what you're wanting? Are you talking about reverse proxy? Or something else?

**Comment by goodpunk6** [comment]
meaning, that when you install nginx and lets say ombi, the install script
will automatically setup a reverse proxy server so you can access ombi at
https://ip.of.atk.server/ombi

**Comment by nemchik** [comment]
Go to `/etc/nginx/sites-available/` and open `AtoMiC-ToolKit-configured-sites`

At the bottom of the file, just before the last `}` add a new line with this: `include /etc/nginx/locations-enabled/*.conf;`

Then create two new folders `/etc/nginx/locations-available/` and `/etc/nginx/locations-enabled/` and create files like `/etc/nginx/locations-available/nzbget.conf` containing

```
location /nzbget {
  proxy_pass http://127.0.0.1:6789;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_redirect off;
}
```

You can make one file for each service and change the /folder on the first line and the :port on the second line. Once you have all the files you can `ln -s /etc/nginx/locations-available/nzbget.conf /etc/nginx/locations-enabled/nzbget.conf`


It might be a decent idea for Atomic to automatically create the `/etc/nginx/locations-available/` folder along with all the files for every service if nginx is installed, but it would still be up to you to `ln` all the specific conf files you wanted into `/etc/nginx/locations-enabled/` unless Atomic were to know already which services you have installed prior to installing nginx and enable them all for you, and then it could auto enable the conf for services as they are installed in the future. Or maybe some kind of option in the nginx menu like 'Detect services for reverse proxy' where Atomic could go down a list of all the services it has a conf for in `/etc/nginx/locations-available/` and see if it gets a response from the `proxy_pass` location, and if yes then it could prompt the end user to enable that conf or something. Just thinking out loud, that's a lot of extra work. Just including the locations folders would probably be a great start for a lot of people.

**Comment by goodpunk6** [comment]
And if you're feeling up to the task, having Letsencrypt  create
certificates to handle all the SSL/TLS stuff. That way users don't get that
pesky error message where you have to click on advanced and proceed (in
chrome and other browser variations)

**Comment by nemchik** [comment]
For let's encrypt here is the config you'll want to place in `AtoMiC-ToolKit-configured-sites` right under the `server_name` line:

```
include /etc/nginx/snippets/letsencrypt.conf;

  location / {
    return 301 https://$host$request_uri;
  }

  # Redirect non-https traffic to https
  if ($scheme != "https") {
    return 301 https://$host$request_uri;
  } # managed by Certbot

}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name {{{same as the server_name line above this, make sure you edit this}}};
  ssl_certificate /etc/letsencrypt/live/{{{your domain}}}/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/{{{your domain}}}/privkey.pem; # managed by Certbot
  ssl_trusted_certificate /etc/letsencrypt/live/{{{your domain}}}/fullchain.pem;
  include /etc/nginx/snippets/ssl.conf;
```

Then create `/etc/nginx/snippets/letsencrypt.conf` and put this in it:

```
location ^~ /.well-known/acme-challenge/ {
	default_type "text/plain";
	root /var/www/letsencrypt;
}
```

And create `/etc/nginx/snippets/ssl.conf` and put this in it:

```
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:50m;
ssl_session_tickets off;

ssl_protocols TLSv1.2;
ssl_ciphers EECDH+AESGCM:EECDH+AES;
ssl_ecdh_curve secp384r1;
ssl_prefer_server_ciphers on;

ssl_stapling on;
ssl_stapling_verify on;

add_header Strict-Transport-Security "max-age=15768000; includeSubdomains; preload";
#add_header X-Frame-Options DENY;
add_header X-Frame-Options SAMEORIGIN;
add_header X-Content-Type-Options nosniff;
```

Then install Certbot and run it (Google is your friend for this, it's pretty straight forward).

I was able to get this working, and the reverse proxy was fine with it too, but it broke nzb360 so I turned the SSL stuff off for now. It could be interesting to have some of this ground work preconfigured in atomic, but it's a bit hard because you have to run Certbot for your domain.

**Comment by TommyE123** [comment]
Hi, Thanks for everyone contributing this this. Its much appreciated. 
I would like to add this going forward.

I've now moved the feature requests over to [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit)

Could you please vote for this there so we can start getting a feel for what people would like to be worked on next.

Thanks
