### ISSUE TITLE
Nextcloud install

### ISSUE THREAD

**Issue by slvrapl** [htpcBeginner/AtoMiC-ToolKit#218]
The problem:
No option for nextcloud install

My Linux distribution and version is: 

- Ubuntu Server 16.04.3

I'm seeing this behaviour on: 
- A fresh install

 I'm not a dummy, so I've checked these!
- I'm using the latest version of AtoMiC-ToolKit. 
- All my Linux distro packages are up to date and I don't see any errors while updating. 
- I've checked there are no current open issues relating to my problem!

**Comment by TommyE123** [comment]
Hi, Thanks for the suggestion. 

I've now moved the feature requests over to [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit)
Could you please vote for this there so we can start getting a feel for what people would like to be worked on next.

Thanks
