### ISSUE TITLE
Emby Server install broken

### ISSUE THREAD

**Issue by DennisFederico** [htpcBeginner/AtoMiC-ToolKit#219]
## The problem
When I try to install emby-server I get the following error message: 
"Invalid option or feature not implemented yet."
This happen either by using the GUI or command line:
> sudo bash setup.sh -i emby-server

### Workaround
Edited "emby-server-repository-configurator.sh" and added 'artful' codename next to 'zesty' (Ubuntu 17.04)

### I'm not a dummy, so I've checked these! 
- I'm using the latest version of AtoMiC-ToolKit.
- All my Linux distro packages are up to date and I don't see any errors while updating.
- I've checked there are no current open issues relating to my problem!

**Comment by TommyE123** [comment]
Hi,

I'll get this fixed over the next few days.

Thanks for your time and investigation work!
Tom

If you want to discuss anything with me please don't hesitate to contact me on [Gitter](http://gitter.im/Tommye123).
Don't forget to vote for new features on [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit) and help drive the focus of [AtoMiC-ToolKit](https://github.com/htpcBeginner/AtoMiC-ToolKit)!
