### ISSUE TITLE
Sonarr not working. What's the install procedure?

### ISSUE THREAD

**Issue by ithelpme** [htpcBeginner/AtoMiC-ToolKit#220]
## The problem
Love this program but it's a hit or miss in terms of what works and what doesn't. It would be great if you could provide the install order because I noticed that when you install some programs in a certain order, it breaks other things. I was able to get all the programs working at one point but I don't remember what order I did the install, especially on program that relies on Mono.  On a fresh install, Sonarr does not work.  Here's my install order. CP, NZbGet, Sonnarr, Hyrda, Deluge and finally Webmin.  This is a fresh install but I restored backup config from another system. I restored CP, NZbGet, Sonnarr, Hydra and Deluge.  CP, NzbGet is working but when I went to test Sonarr, it's broken. Service failed to restart.  I've restarted entire computer but it doesn't work.

### My Linux distribution and version is: 
- Ubuntu Desktop 16.04 LTS

### I'm seeing this behaviour on: 
- A fresh install

### I'm not a dummy, so I've checked these!
- I'm using the latest version of AtoMiC-ToolKit.

**Comment by thinkbig1979** [comment]
Sonarr not working for me either (radarr either for that matter).

Here's the terminal output from during the install.

`--->Enabling Sonarr Autostart at Boot...
Created symlink from /etc/systemd/system/multi-user.target.wants/sonarr.service to /etc/systemd/system/sonarr.service.
sonarr.service SystemD script added and enabled

--->Starting Sonarr...
sonarr.service is now: inactive
Waiting for Sonarr to finish initial setup

--->Stopping Sonarr...
sonarr.service is now: inactive

--->Setting permissions...
chown: cannot access '/opt/NzbDrone': No such file or directory
chmod: cannot access '/opt/NzbDrone': No such file or directory
chmod: cannot access '/opt/NzbDrone': No such file or directory
/opt/NzbDrone Done

--->Starting Sonarr...
sonarr.service is now: inactive

--->All done. Sonarr installation complete.
For access details, run the Sonarr Access Details utility.`

**Comment by TommyE123** [comment]
Hi,
Thanks for posting the log of the install. 

Its suggesting that Sonarr isn't even being installed or has possibly moved directories?!? Was there any errors further up?

**Comment by thinkbig1979** [comment]
No problem. Here's the entire thing:

  AtoMiC Sonarr Installer Script

Press [Enter] key to continue or Ctrl+C to exit...


--->Stopping Sonarr...
Nothing found to stop

--->Removing Sonarr Systemd Startup scripts...
sonarr.service SystemD script not found

--->Removing Sonarr Init.d startup scripts...
/etc/init.d/sonarr init script not found

--->Removing Sonarr default config scripts...
/etc/default/sonarr default script not found

--->Adding Sonarr repository...
Sonarr repository already exists

AtoMiC Mono Installer Script

--->Adding Mono repository...
Mono repository already exists

--->Refreshing packages list...
W: https://minergate.com/repo/deb/dists/stable/InRelease: Signature by key 33BDA78F1D398B52D01438F603F0D99C2EC4C39D uses weak digest algorithm (SHA1)
Done

--->Installing prerequisites for Mono...
Reading package lists... Done
Building dependency tree
Reading state information... Done
libmono-cil-dev is already the newest version (5.4.1.6-0xamarin1+ubuntu1604b1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

--->Installing Mono...
Reading package lists... Done
Building dependency tree
Reading state information... Done
mono-complete is already the newest version (5.4.1.6-0xamarin1+ubuntu1604b1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
---> Mono installation complete.

--->Installing Sonarr...
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nzbdrone


--->Stopping Sonarr...
Nothing found to stop

--->Autostart configuring...
Using systemd

--->Removing Sonarr Init.d startup scripts...
/etc/init.d/sonarr init script not found

--->Removing Sonarr default config scripts...
/etc/default/sonarr default script not found

--->Enabling Sonarr Autostart at Boot...
Created symlink from /etc/systemd/system/multi-user.target.wants/sonarr.service to /etc/systemd/system/sonarr.service.
sonarr.service SystemD script added and enabled

--->Starting Sonarr...
sonarr.service is now: inactive
Waiting for Sonarr to finish initial setup

--->Stopping Sonarr...
sonarr.service is now: inactive

--->Setting permissions...
chown: cannot access '/opt/NzbDrone': No such file or directory
chmod: cannot access '/opt/NzbDrone': No such file or directory
chmod: cannot access '/opt/NzbDrone': No such file or directory
/opt/NzbDrone Done

--->Starting Sonarr...
sonarr.service is now: inactive

--->All done. Sonarr installation complete.
For access details, run the Sonarr Access Details utility.

Thank you for using the AtoMiC ToolKit.
Please visit http://forum.htpcbeginner.com to discuss or raise any issues.
You can also follow htpcBeginner through Facebook, Twitter, Google+, YouTube, or RSS.


Press [Enter] key to continue or Ctrl+C to exit...

**Comment by Dnkhatri** [comment]
Do you have a sonarr directory instead of Nzbdrone in the opt. If I recall correctly there was a commit about changing the install directory on the sonarr github some time ago.

**Comment by TommyE123** [comment]
Looking at the install logs, my guess is something could be wrong with the repository that's currently setup in either `/etc/apt/sources.list or /etc/apt/sources.list.d`

This section taken from the posted install log below means Sonarr isn't available as a package to install. 
`--->Installing Sonarr...
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nzbdrone`

I can't seem to replicate this issue on my VM's and the tests that run every night at [Travis.ci](https://travis-ci.org/htpcBeginner/AtoMiC-ToolKit/builds) don't appear to be failing which suggest it's not a directory issue, but really appreciate the offer of help @Dnkhatri

Did you attempt an install of Sonarr before using AtoMiC-ToolKit? I would try a simple uninstall and then reinstall first. 

I'm also wondering if the hardware/software combination your using isn't somehow currently supported?

Else can either/both of you contact me on [Gitter](http://gitter.im/Tommye123) if your still having issues and I'm sure we can get this sorted.

**Comment by thinkbig1979** [comment]
I'm actually running it in an Ubuntu LX zone on SmartOS, so could be that that is somehow not cooperating.

**Comment by flawless-victory** [comment]
I had this same issue a couple days ago on Ubuntu 16.04 and as mentioned previously no /opt/NZbDrone directory was created. 

Not saying this will work for anyone else but I was able to get it working by reinstalling it through the toolkit a second time. Hope this can help someone or provide a solution or a potential idea of what the issue might be to the dev. 

Thanks for the toolkit btw. It’s a great time saver and much appreciated.

**Comment by TommyE123** [comment]
Thanks @flawless-victory for offering help with this. 

The no `/opt/NZbDrone directory` is the result of the install failing on `E: Unable to locate package nzbdrone`

I'd try a remove and reinstall if that's not been done already.

@thinkbig1979 or @ithelpme
I've sent you a few messages on [Gitter](https://gitter.im). Give me a shout and I'll try and get this working for you. I've been helping a few others lately with other issues on `Gitter` and this is one I'm keen to find out what's wrong so I can fix it if possible in ATK.

Thanks.
Tom

**Comment by TommyE123** [comment]
@thinkbig1979 is now up and running with `Sonarr` and `Radarr` 
As this has been open since Nov and i'm not currently aware of any issues with either service im going to close this.

@ithelpme if your still having issues, can you reply to this on here or contact me privately on [Gitter](https://gitter.im/Tommye123).

**Comment by cybercussion** [comment]
I have the same issue.  I guess doing a dist-upgrade on ubuntu put this into a death spin.  `sudo apt install nzbdrone' does not re-create /opt/NzbDrone.  I tried --reinstall.  It claims its pulling down 3.0.6 but the folder path never shows up.
Could just be this old ODROID XU4 ran its course and the time vampire aspect has me re-thinking how I want to waste the hours of my weekend :)

**Comment by nemchik** [comment]
This project is no longer maintained. We've moved on to https://dockstarter.com/
