### ISSUE TITLE
Request: back up custom "/etc/nginx/sites-enabled/" files instead of deleting

### ISSUE THREAD

**Issue by zybeon** [htpcBeginner/AtoMiC-ToolKit#221]
## The problem
When installing Organizer (and I assume some others) the script deletes all existing nginx configs in "/etc/nginx/sites-enabled/". I happened to have a large number of services already setup in nginx using reverse proxies as well as letsencrypt and ngxblocker as well as a number of other custom settings. 

If there is no backups currently being made I suggest they be implemented or at least an initial check and a warning notice that files will be deleted.

### My Linux distribution and version is: 
- Ubuntu Server 17.04

### I'm seeing this behaviour on: 
- First time using AtoMiC-ToolKit on an existing setup

### I'm not a dummy, so I've checked these!
I updated with 'git pull' before running.
I selected to install organizr.

**Comment by TommyE123** [comment]
I'm really sorry this has happened and I've not got back to you sooner only I've been away on holiday.
Your quite right it shouldn't be deleting anything. For some reason (which I can't remember why) it uninstalls nginx before it adds the new official repository and installs the latest version. I imagine this process is what's causing that. I'm hoping I can change it so it doesn't uninstall first and just updates if required however I need to test this first to check it works ok. If not I'll look at other options and take on-board your suggestion.

So my apologies and although it won't help you get your files back I'll change it for future installs.

I'll keep this open for now so I can give a full update on what the end result and fix is.
Tom

**Comment by TommyE123** [comment]
This has now been implemented and will not uninstall `Nginx` first which was causing everything to be deleted. It also now backs up the main nginx.conf file if there is one.
