### ISSUE TITLE
Deluge Install fails at Configuring Deluge Settings

### ISSUE THREAD

**Issue by 1agent13** [htpcBeginner/AtoMiC-ToolKit#224]
## New features
Please visit http://feathub.com/htpcBeginner/AtoMiC-ToolKit

## The problem
Installing Deluge which fails at section Configuring Deluge Settings.
Error message is; "sed: can't read /home/user/.config/deluge/core.conf : No such file or directory"
Modifying copy_torrent_file in /home/user/.config/deluge/core.conf failed

### My Linux distribution and version is: 
- Ubuntu Server 16.04.3

### I'm seeing this behaviour on: 
- A fresh install

### Link to install logs
- Do not know where to local the install log.

### I'm not a dummy, so I've checked these!
- I'm using the latest version of AtoMiC-ToolKit. 
- All my Linux distro packages are up to date and I don't see any errors while updating. 
- I've checked there are no current open issues relating to my problem!

**Comment by TommyE123** [comment]
Hi, Thanks for logging this and im sorry your having issues,

I couldn't immediately replicate this however I do want to change a few things around the install of Deluge. There's a 10 second sleep in the script to give Deluge enough time to startup and create the config file. I'm wondering if it just didnt start in time and so didnt create the config file? I'm going to tweak a few things and increase the wait time and see if that helps.

p.s 
When I say the install logs I mean just the text which is displayed as its installing on the terminal window. However unless you have a desktop this isn't that easy to capture, but you've give me the error anyway so its not a problem!!

Tom

**Comment by TommyE123** [comment]
I've applied some fixes to Deluge so please could you update to the latest version of the Toolkit and try removing deluge and reinstalling?
Thanks

**Comment by hughker** [comment]
@TommyE123 I'm experiencing this too on Ubuntu 16.04 my log file is here » http://cl.ly/1o1f3B3V0M0J

**Comment by TommyE123** [comment]
@1agent13 
I helped @hughker get his setup working with a quick chat on [Gitter](https://gitter.im). I'm aware of a potential missing dependency for Deluge and I can help you install it if its the same problem.

Would you be able to contact me on [Gitter](https://gitter.im) if you are still having issues?

Thanks
Tom

**Comment by aDarkling** [comment]
I'm trying out Atomic Toolkit on a virgin Ubuntu 17.10 install now.
Same problem.  I'll try you on Gitter.

**Comment by TommyE123** [comment]
@aDarkling Can you give that another try after getting the latest commit. 
You may still get an error trying to Add the Repository however it will just carry on and hopefully create the missing core.conf later on.

Let me know how you get on either on here or Gitter.

Thanks
Tom

**Comment by aDarkling** [comment]
@TommyE123, you just had to give it a chance to fix itself?
Nice catch!  It worked!
Thanks so much!
