### ISSUE TITLE
PlexPY inactive after install

### ISSUE THREAD

**Issue by Chudz** [htpcBeginner/AtoMiC-ToolKit#229]
## The problem
Fresh install of Ubuntu Minimal just installed AtoMiC-ToolKit and installed Plex Media Server, Sonarr, Radarr, Ombi without problems. Then I tried to install PlexPY and it is not starting up.  I have the Access Details log here.

--->Searching for possible port numbers...
Default port: 8182 found in AtoMiC-ToolKit config.
Configured port: 8182 found in /opt/plexpy/config.ini.
Error: near line 1: no such table: users

--->Finding PlexPy System details...

You may be able to access PlexPy on any of the following URLs...
--->http://111.11.11.111:8182 from anywhere (requires port forwarding on router)
--->http://111.11.11.111:8182 from your local network
--->http://hostname:8182 from your local network
--->http://localhost:8182 on this system
Actual port numbers could be different. Check your settings file: /opt/plexpy/config.ini
If SSL is enabled, then use HTTPS instead of HTTP in the above URLs.

Your PlexPy credentials are...
--->Username: Cannot determine or username not set.
--->Password: Not displayed for security.

Checking PlexPy status...
SYSTEMD plexpy.service found.
plexpy.service is currently: inactive
PlexPy is configured to be accessible outside localhost.

Thank you for using the AtoMiC ToolKit.
Please visit http://forum.htpcbeginner.com to discuss or raise any issues.
You can also follow htpcBeginner through Facebook, Twitter, Google+, YouTube, or RSS.

### My Linux distribution and version is:
Ubuntu Server 16.04.3

### I'm seeing this behaviour on:
A fresh install
First time using AtoMiC-ToolKit on an existing setup

### I'm not a dummy, so I've checked these!
I'm using the latest version of AtoMiC-ToolKit.
All my Linux distro packages are up to date and I don't see any errors while updating.
I've checked there are no current open issues relating to my problem!

**Comment by TommyE123** [comment]
Hi @Chudz , 
Thanks for logging the issue. 

If you try the `PlexPY` install again do you see any errors along the way? or even better can you post the install log for me and I'll take a look. (just stick it in a [Gist](https://gist.github.com) if possible)

Tom

**Comment by Chudz** [comment]
After going through the install again its working :) thanks for the help! best tool ever!

**Comment by TommyE123** [comment]
It really should have worked first time so apologies, however I'm glad its working now for you!
Are you ok to close this issue now?

Regards
Tom

p.s If you've not seen it already you can vote for future new features on [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit), Some of which are already being worked on!

**Comment by Chudz** [comment]
Nice! thanks :) i'll close this issue.
