### ISSUE TITLE
setup.sh [question]

### ISSUE THREAD

**Issue by carrigan98** [htpcBeginner/AtoMiC-ToolKit#23]
Can the setup.sh script accept more than one argument, ex. Install sickrage and couchpotato?

**Comment by htpcBeginner** [comment]
Not at this point. But it is a feature we can implement.

**Comment by carrigan98** [comment]
Something like this?
http://1.bp.blogspot.com/_yqqceaP4wog/Szl0XUVk-7I/AAAAAAAACUc/MAyJuwvumpc/s400/unix-dialog-checklist-shell-script.JPG

**Comment by htpcBeginner** [comment]
Definitely possible. The couchpotato sickbeard restore scripts already use the dialog package.

**Comment by carrigan98** [comment]
Pull request #34 adds dialog support, thus closing this question.

**Comment by htpcBeginner** [comment]
@carrigan98 I completely rewrote the toolkit. Dialog is now not required. I redid the menus using whiptail which is included in the base install. Sorry I could make much use of the work you did on dialog.
