### ISSUE TITLE
Radarr Install failure

### ISSUE THREAD

**Issue by nathan0726** [htpcBeginner/AtoMiC-ToolKit#231]
## New features
Please visit http://feathub.com/htpcBeginner/AtoMiC-ToolKit

## The problem
Attempting new install of Radarr with the newest version of ATK. Once the script gets to the point of downloading Radarr the entire VM (ESXi 6.5) freezes. Installing Sonarr however, works without issue. 

### My Linux distribution and version is:
Linux Mint 18.3
Also, reproduced same issue on Ubuntu 17.10

### I'm seeing this behaviour on:
A fresh install

### I'm not a dummy, so I've checked these!
- I'm using the latest version of AtoMiC-ToolKit. 
- All my Linux distro packages are up to date and I don't see any errors while updating. 
- I've checked there are no current open issues relating to my problem!

**Comment by TommyE123** [comment]
hi @nathan0726, 

Thank for logging an issue.
Whats the last line you see before it hangs?

I've noticed there could be a dependency missing from ATK.
Can you just check you have the `grep` package installed?

Give me a shout on [Gitter](https://gitter.im/Tommye123) and we can try a few things to get this working.

Tom

**Comment by nathan0726** [comment]
Hey @TommyE123 
I sent you a message on Gitter. I'll post here too just in case you see this first. 
I've verified that Grep is installed and working. Here is a screenshot at the point of freezing when installing:
[https://imgur.com/a/nOVwD](url)

**Comment by TommyE123** [comment]
@nathan0726 
Are you still having a problem?
It sounds like after speaking to you briefly on Gitter that you have a general issue downloading that link to the Radarr files and its not related to ATK.

Please can you close this off if its no longer required.

Thanks.
Tom
