### ISSUE TITLE
NZBHydra 2

### ISSUE THREAD

**Issue by estimadarocha** [htpcBeginner/AtoMiC-ToolKit#232]
When do you plan to add NZBHydra 2?

Thanks

**Comment by TommyE123** [comment]
I've not looked into this as we are actively working on delivering the most voted for new features on [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit).

Please could you request this there so its logged and we can look into adding it. Please add as much detail as possible what's required. ie which `github` branch we need to move to if required would be handy.

Thanks
Tom

**Comment by estimadarocha** [comment]
yes i mean that one.... i did the suggest!

**Comment by TommyE123** [comment]
Nice one. 
Don't forget to vote for it ;-)
