### ISSUE TITLE
Plex not installing on Ubuntu Server 17.10

### ISSUE THREAD

**Issue by aDarkling** [htpcBeginner/AtoMiC-ToolKit#234]
## New features
Please visit http://feathub.com/htpcBeginner/AtoMiC-ToolKit

## The problem
Plex Media Server fails to install because of repository configuration error  (kinda like Deluge).
Then it exits completely out of ATk.

Its a known problem.  I found these references to it:
https://forums.plex.tv/discussion/284454/repository-not-working-for-me/p3
https://forums.plex.tv/discussion/297191/plex-repo-no-longer-working-form-ubuntu-17-10
https://www.reddit.com/r/PleX/comments/630y4t/plex_repo_not_working_on_ubuntu_1704/
https://forums.plex.tv/discussion/268238/ubuntu-17-04-repository/p1?new=1

### My Linux distribution and version is: 
Almost virgin Ubuntu Server 17.10 installation.  Only AtoMiC-ToolKit has touched it. 

### I'm seeing this behaviour on: 
Installation & attempted uninstall/reinstall cycles

### Link to install logs
Not sure which install logs you need, but here's the output that I get every time:

AtoMiC Plex Media Server Installer Script

--->Stopping Plex Media Server...
Nothing found to stop

AtoMiC FFmpeg Installer Script
Available Version: 3.4.1
Installed Version: 3.4.1
Update not required

--->Adding Plex Media Server repository...
deb https://downloads.plex.tv/repo/deb ./public InRelease

--->Adding Plex Media Server Keys...
OK

--->Refreshing packages list...
E: The repository 'https://downloads.plex.tv/repo/deb ./public Release' does not have a Release file.
E: The repository 'http://ppa.launchpad.net/deluge-team/ppa/ubuntu artful Release' does not have a Release file.
Done

--->Creating Plex Media Server files / folders...
Creating /var/lib/plexmediaserver...
...created.

--->Stopping Plex Media Server...
Nothing found to stop

--->Autostart configuring...
Using systemd

--->Removing Plex Media Server Init.d startup scripts...
/etc/init.d/plexmediaserver init script not found

--->Removing Plex Media Server default config scripts...
/etc/default/plexmediaserver default script not found

--->Enabling Plex Media Server Autostart at Boot...
Created symlink /etc/systemd/system/multi-user.target.wants/plexmediaserver.service → /etc/systemd/system/plexmediaserver.service.
plexmediaserver.service SystemD script added and enabled
plexmediaserver.service SystemD override script added

--->Updating systemd to run as rdash ...
OK

--->Installing Plex Media Server...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package plexmediaserver

--->Enable Sources file...
Update not required

--->Stopping Plex Media Server...
plexmediaserver.service is now: failed

--->Autostart Removing any unrequired files...
Using systemd so removing any sysv-init files

--->Starting Plex Media Server...
plexmediaserver.service is now: activating
watch@AkwardNAS:/opt/AtoMiC-ToolKit/plexmediaserver$

**Comment by TommyE123** [comment]
Thanks for logging this,

Looking quickly at the `Plex repository`, it doesn't currently appear to support `Artful 17.10`. I obviously have no idea if they plan to support it in future but at a complete finger in the air guess I think they may have to at some point.

I'm going to put in a check for the time being to say that `Artful` ins't currently supported. There's probably other ways to get it working, however we are currently working on other features at present and I think this would take some time to get working and implement.

Please also bear in mind that 17.10 only has a 9 month support life and ends in July 2018. [Artful Release Notes](https://wiki.ubuntu.com/ArtfulAardvark/ReleaseNotes).

I would also suggest you add it to [http://feathub.com/htpcBeginner/AtoMiC-ToolKit](http://feathub.com/htpcBeginner/AtoMiC-ToolKit) so we can see how popular this would be to implement which could bring the development forward. (when the website comes back up!)

However If anyone wants to code this up, please feel free!!

thanks
Tom
