### ISSUE TITLE
Give option to use beta branch of PlexPy

### ISSUE THREAD

**Issue by mrowlinson** [htpcBeginner/AtoMiC-ToolKit#238]
PlexPy is being replaced by Tautalli. https://www.reddit.com/r/PleX/comments/7kmhl3/its_finally_here_tautulli_v2_beta_formerly_plexpy/

Can you give us the option to use the beta branch from their git so we can use this new version? Or show what in the script to edit to pull the beta branch instead of master? I'm totally fine with editing the script myself to switch branches.

**Comment by josharmour** [comment]
I would also like this.  As a workaround, can't we just update by going to /opt/plexpy and executing 

`git pull https://github.com/JonnyWong16/plexpy.git`

I'm inferring based on the linux instructions here: 

https://github.com/JonnyWong16/plexpy/wiki/Installation

**Comment by mrowlinson** [comment]
I tried switching branches by using 

`git checkout beta`

Didn't even cross my mind to just repull the git. I'm a dope.

**Comment by josharmour** [comment]
Did this work for you?  I'm about to upgrade.

**Comment by mrowlinson** [comment]
I decided to just install a separate instance of it instead and run them simultaneously for the time being.

**Comment by nemchik** [comment]
Changing branch worked for me a long time ago (I switched over within a day or two of the Reddit post referenced). I've spoken with @TommyE123 about this and stated my opinion is that until the new version is out of beta or the dev recommends it as the preferred install I think ATK should not switch to the new version yet.

**Comment by nemchik** [comment]
Tautulli is now officially released. If you have PlexPy installed through atk you can either use PlexPy's built in updater or use atk's update menu and you will be updated to Tautulli. If you don't have PlexPy installed then choosing to install PlexPy will actually install Tautulli. Sometime in the future atk will replace the PlexPy name in the menus with Tautulli.

**Comment by nemchik** [comment]
Release announcement for reference: https://www.reddit.com/r/PleX/comments/83gmnt/the_tautulli_v2_release_is_finally_here_plexpy_is/

**Comment by mrowlinson** [comment]
I used atk to update it and it broke my installation.

**Comment by BJWTech** [comment]
For whatever reason, mine is stuck on plexpy. I updated via setup.sh and navigated to plexpy. Selected manually update. I saw that it pulled some data. But the webapp still is plexpy, and still says so many commits out of date. Try to update via webapp. Nothing seems to happen as I am behind the same number of commits.

**Comment by nemchik** [comment]
This sounds like a permissions issue. Can you run `sudo chown -R ($id -un): /opt/plexpy/` and then try updating through atk again?

**Comment by nemchik** [comment]
I should have mentioned, this assumes you assigned atk to run as the user you're logged in as

**Comment by BJWTech** [comment]
nemchik; All files are owned by my user.

**Comment by BJWTech** [comment]
nemchik; I'm going the following when updating via at;

Please, commit your changes or stash them before you can merge.
Aborting

**Comment by nemchik** [comment]
`cd` into the directory and run `git status` and post the output here.

Likely in going to tell you to `git reset HEAD --hard` but let's see what it's complaining about first.

**Comment by BJWTech** [comment]
I followed faq #5. Got it fixed.

**Comment by mrowlinson** [comment]
I tried running the chown command and got the following error.

-bash: syntax error near unexpected token `('

**Comment by nemchik** [comment]
Oh shoot the `$` should be outside the `(`

Like this: `sudo chown -R $(id -un): /opt/plexpy/` but as @BJWTech pointed out, you might need to follow this https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q5

**Comment by mrowlinson** [comment]
I completed deleted everything, ran the install from atk, ran the git commands from the FAQ, and it’s still not working. I get the following when I try to start the service.

`● plexpy.service - Tautulli - Stats for Plex Media Server usage
   Loaded: loaded (/etc/systemd/system/plexpy.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Sat 2018-03-10 22:23:24 EST; 29s ago
  Process: 2951 ExecStart=/opt/Tautulli/Tautulli.py --quiet --daemon --nolaunch --config /opt/Tautulli/config.ini 

Mar 10 22:23:24 exuma systemd[1]: plexpy.service: Service hold-off time over, scheduling restart.
Mar 10 22:23:24 exuma systemd[1]: Stopped Tautulli - Stats for Plex Media Server usage.
Mar 10 22:23:24 exuma systemd[1]: plexpy.service: Start request repeated too quickly.
Mar 10 22:23:24 exuma systemd[1]: Failed to start Tautulli - Stats for Plex Media Server usage.`

**Comment by nemchik** [comment]
Did you stop the service before running the git commands from the FAQ?

**Comment by mrowlinson** [comment]
Yes.

**Comment by nemchik** [comment]
You could use atk to make a backup on PlexPy and then uninstall it and reinstall it from atk. You'll lose your config (thus the backup) but you should be able to get it working. From there you can restore your config and database if needed.

**Comment by mrowlinson** [comment]
I did do that and that still what’s happening.

**Comment by mrowlinson** [comment]
I notice the process it’s trying to start is in /opt/Tautulli which does not exist. I tried to McDonald’s the plexpy directory to that name but still get that error.

**Comment by nemchik** [comment]
A fix has been prepared in atk and should be released tomorrow.

**Comment by TommyE123** [comment]
I've now committed the changes to hopefully fix this. Please can you report back with how you all get on :-)

Thanks.

**Comment by mrowlinson** [comment]
That worked, however, you may want to make a change so when trying to restore from a backup that it looks for PlexPy and Tautulli backups, not just Tautulli. I’ve got to manually restore my config and db since it can’t see my PlexPy backups but that’s not a big deal.

**Comment by TommyE123** [comment]
I'm going to close this as I'm assuming this is working for most people now.
I'll take on board the backup suggestion so thanks for that and @mrowlinson for reporting back with the outcome.

Tom
