### ISSUE TITLE
Can you add a n option to create nightly cronjob to backup installed services?

### ISSUE THREAD

**Issue by mahenkpatel** [htpcBeginner/AtoMiC-ToolKit#239]
I know there is an option to run auto update of all the services using cron. can you add a similar script to run backup of all the installed services so we can create a cronjob to automate backups?

Thanks

**Comment by TommyE123** [comment]
Hi, thanks for the request. 

This is currently on the [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit) backlog and will be worked on very soon. We are just currently trying to finish off adding the `Reverse Proxy` functionality. Please don't forget to vote on [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit) as we do try to work on the most requested features.

If anyone wants to help in any way at all with `AtoMiC-ToolKit`, please don't hesitate to contact me. Even if you don't have any experience but willing to learn the basics, There's tons of tasks which need doing. (like this nightly backup job!)
