### ISSUE TITLE
Ombi v3 installer added

### ISSUE THREAD

**Issue by mrowlinson** [htpcBeginner/AtoMiC-ToolKit#240]
Ombi was recently updated from version 2 to version 3. The updater and installer in the toolkit are now broken. If you watch the update/install progress it’s trying to download and install the ARM version and it fails. I’ve tried completely uninstalling and reinstalling but it fails in the same way.

**Comment by TommyE123** [comment]
Thanks logging the issue.

Its going to need to have the install\update process changed to fix this. I will try to get around to doing it this week.

**Comment by mrowlinson** [comment]
Any update on this? Really want to get it reinstalled since I uninstalled my copy when trying to troubleshoot the issue.

**Comment by TommyE123** [comment]
I'm working on it right now ;-)

**Comment by nemchik** [comment]
FYI were still waiting on [this](https://github.com/Unimatrix0/update_ombi/pull/20) to merge. Once that's accepted we should be in better shape to get ombi v3 into atk.

**Comment by janipewter** [comment]
Following

**Comment by postmanpaul** [comment]
--->Downloading files...
--2018-03-16 13:13:01--  https://github.com/tidusjar/Ombi/releases/download/v3.0.3030/linux-arm.tar.gz arm version?
then..  
--->Extracting files...
unzip:  cannot find or open /tmp/ombidownload/*.zip, /tmp/ombidownload/*.zip.zip or /tmp/ombidownload/*.zip.ZIP.

No zipfiles found.
mv: cannot stat '/tmp/ombidownload/extract/Release/*': No such file or directory

--->Starting Ombi...
ombi.service is now: activating

ls /opt/ombi/
Ombi.sqlite

... this is wrong.. :) just wanna show you what´s wrong, if it might work in your computer. 

Greets Postmanpaul.

**Comment by mrowlinson** [comment]
Looks like the merge was committed 2 days ago. Any update on this?

**Comment by TommyE123** [comment]
The merge wasn't ready so it was reversed, however this isn't far away from being ready now :-)

I've got round all the issues I was facing with the their update scripts and it seems to be working correctly in my Dev branch.
I just need to do a couple of final tests (Arm device being one of them) and I'll push the new installer up.

#### couple of points to note when I do:
- Currently it won't work if you have `rtorrent\rutorrent` installed as well. The new `Ombi` uses port 5000 which is the same port rtorrent uses behind the scenes. I think we might be able to get away with changing the rtorrent port to 5001. I'll submit a separate 

- You cannot migrate your old data over from the previous install. This is a limitation of `Ombi` not `ATK`

- I also go on holiday for a week tomorrow, so  I want to push this today if I can ; -)

- Please can people post if it works for them once its pushed up and if poss what they have it working on!

Thanks
Tom

**Comment by postmanpaul** [comment]
Just let me know when i can test, i want to help as much as i can :)

**Comment by TommyE123** [comment]
OK its committed! Fingers crossed then, as im going away i've decided to push now and see how the community reacts!

@postmanpaul and @mrowlinson and anyone else who installs this please can you report back with how you get on.

Please note the reverse proxy isnt working in some scenarios.

Please also make sure you set an APIKEY in Ombi settings in order to check for the latest version correctly to save downloading every time you try and update. There will be improvements going forward im sure. However I think you've all waited long enough and this should be a good start to get it up and running :-)

thanks for your patience, This has been quite a tough one to get over the line.

Regards
Tom

**Comment by nemchik** [comment]
If https://github.com/tidusjar/Ombi/issues/2070 gets solved (@tidusjar seemed open to this request) then an API key will be set automatically when it's found to be blank or missing. That's not in yet to my knowledge though. I just tested the Manual Update and it seemed to work fine (I went from Ombi v3 develop branch to Ombi v3 master by running that, upgrades from Ombi v2 should go smooth I think.)

**Comment by mrowlinson** [comment]
Working for me now as well. Thanks for the update!

**Comment by postmanpaul** [comment]
Damm! i like this!! thx alot!! ;D

**Comment by samsepiol59** [comment]
So does the installer work now? Or just the updater?

**Comment by TommyE123** [comment]
Both should be working fine now. Are you having problems?

**Comment by samsepiol59** [comment]
I don't know, I wanted to be sure before installing! :-) I'll give it a try as soon as I get back home from work, thanks for the good work!

**Comment by TommyE123** [comment]
No problem. Can u let us know how you get on? I'll probably close this issue then.

**Comment by samsepiol59** [comment]
Of course, I'll let you know in 3h maximum! Thanks!

**Comment by samsepiol59** [comment]
@TommyE123 It works!! Thank you so much!

**Comment by TommyE123** [comment]
Thanks for letting us know. There was a slight error in the update scripts which have now been fixed. I would suggest updating `ATK` if your using `Ombi`.

**Comment by Digmarx** [comment]
I'm having issues with the reverse proxy. Calling Ombi via internal IP works as expected, but it seems no matter what .conf settings I use I get text label issues identical to [this](https://user-images.githubusercontent.com/1707290/32136637-157ea70c-bc09-11e7-8f93-7e07b6bccb18.png``)

**Comment by TommyE123** [comment]
@Digmarx, are you ok now? 
I see you didn't need the other issue you raised?

**Comment by tidusjar** [comment]
It's because you are blocking json files in your config

**Comment by nemchik** [comment]
@tidusjar this repo is? Can you point out where? I didn't realize this. I've got a branch with an updated nginx config in the works and I've not had any issues with the config, but I'd like to make sure it's not actually causing issues.

**Comment by tidusjar** [comment]
No, this happens when users nginx config is denying access to json files, emby and ombi will break. Ombi relies on it for the translations

**Comment by Digmarx** [comment]
Yes, this was the case. On the Organizr wiki there was a bit about authentication that included blocking json/db/log files. I had configured that before installing emby and ombi and then forgotten about it. It appears that the Organizr wiki has been edited to remove that bit. So all's well, no harm to anything other than my ego :)

**Comment by TommyE123** [comment]
Thanks for letting us know. 
I'm going to close this now as I think this is now working ok. 
There will be some security improvements coming for reverse proxy for `Ombi` over the next few weeks.
