### ISSUE TITLE
nginx invalid parameter "http2"

### ISSUE THREAD

**Issue by trohnjavolta** [htpcBeginner/AtoMiC-ToolKit#243]
## The problem
Nginx service fails. I installed it along with organizr website. 
Nginx states invalid parameter "http2".
Removing these 2 lines in `/etc/nginx/sites-enabled/AtoMiC-ToolKit-configured-sites:`
```
listen       443 ssl https;
  listen       [::]:443 ssl https;
```
fixes it.
I'm not experienced with nginx at all, but I read HTTP/2 on nginx requires at least 1.9.5.
Nginx version is 1.6.2... I guess that's the issue.
Updating nginx via Atomic Toolkit doesn't help, it states no updates avaiable and stays same version.

### My Linux distribution and version is: 
- Armbian (heavily optimized os for arm boards) with Debian jessie as base

**Comment by nemchik** [comment]
@trohnjavolta Can you try reading through this thread https://forum.armbian.com/topic/640-prefer-nginx-and-mariadb-from-other-repositories-newer-versions/ and installing a newer version of nginx via the debian repository and letting us know if http2 works for you?

We'll try and figure out if this is a feasible solution or if we're better off changing the config. There are some benefits to http2 that I would hate to see us lose.

**Comment by trohnjavolta** [comment]
A lot of new stuff for me in the link. I noticed that there is a jessie-backports repository and it has nginx in version 1.10.3. This repo is already present in armbian.
Furthermore I read that all backports are deactivated by default. 
With apt-get -t jessie-backports install nginx` I could update to version 1.10.3. Readded the 2 lines and so far everthing works.

**Comment by nemchik** [comment]
We've got some other things in the works right now, but it would be good for us to make a decision to either remove the 2 or add some way to check that we've got the minimum version of nginx installed.
