### ISSUE TITLE
Sonarr doesn't work after update using -U

### ISSUE THREAD

**Issue by vrokolos** [htpcBeginner/AtoMiC-ToolKit#244]
I'm on raspbian. It worked perfectly fine before update. It won't write any logs and I can't figure out what the actual error is. Perhaps you can help me trace it?

Feb 28 10:44:50 osmc systemd[1]: Started Sonarr.
Feb 28 10:44:52 osmc mono[16309]: Press enter to exit...
Feb 28 10:44:53 osmc systemd[1]: sonarr.service: Main process exited, code=exited, status=1/FAILURE
Feb 28 10:44:53 osmc systemd[1]: sonarr.service: Unit entered failed state.
Feb 28 10:44:53 osmc systemd[1]: sonarr.service: Failed with result 'exit-code'.
Feb 28 10:44:53 osmc systemd[1]: sonarr.service: Service hold-off time over, scheduling restart.
Feb 28 10:44:53 osmc systemd[1]: Stopped Sonarr.

**Comment by TommyE123** [comment]
This is most likely related to the issue logged here [Sonarr Wont start#2431](https://github.com/Sonarr/Sonarr/issues/2431)
We currently use the Stable version of `Mono` which has been updated and appears to have broken `Sonarr`

It seems they have a fix that they've pushed to the `Sonarr` Dev branch but are just testing it at the moment... 
I would hold tight for the minute and lets see what happens. `ATK` Should be able to cope with automatically fixing it once its been merged up.

I think this could have possibly affected a few services which use `Mono`:
`Radarr`
`Jackett`

**Comment by vrokolos** [comment]
Ah thanks. I'll just wait for an update then.

**Comment by dutch2005** [comment]
If and only if you know what your doing :)

https://download.sonarr.tv/hotfixes/regression-mono-5.10/NLog.dll.gz

replace (or just rename the current Nlog.dll to something like NLog.dll.old) NLog.dll with the above file.

Note: This file is from the dev section. (majority of sonarr will work).

**Comment by Mohammed-JS-Khan** [comment]
Not sure if this is at all related to this issue. I reinstalled my whole server yesterday. After installing `ATK` I was trying to get `SABnzbd`, `Sonarr`, and `Radarr`. `SAB` was fine but `Sonarr` and `Radarr` both had issues. The both seem to install fine but they stay in "inactive" state and both claim that the `config.xml` does not exist (somewhere under the home dir).

I can link screenshots later in the evening today.

Just want to know if that would have to be a new issue or if it may be related to this ongoing `Mono` issue.

**Comment by lordraiden** [comment]
When it will be fix and available as an update, are we talking about days? Weeks?
Thanks

**Comment by TommyE123** [comment]
Thanks @Mohammed-JS-Khan for the explanation. 

As mentioned above, this isn't a problem with `ATK`. [Sonarr](https://github.com/Sonarr/Sonarr), [Radarr](https://github.com/Radarr/Radarr) and [Jackett](https://github.com/Jackett/Jackett) all have issues logged on their `github` sites related to this, so a fix is completely dependant on when they decide to push the new `NLog.dll` into the master branches. When they do a simple update in `ATK` will pick it up and apply it automatically.

I have no immediate plans to fix this in `ATK` as I imagine that they will get a fix out soon but obviously I have no idea when!

**Please remember that I do this pretty much completely on my own, in my own time for fun, for free**. I only took over the admin rights to this github when it became easier when i was pushing a lot of fixes up when all the old devs faded away. I'm struggling to keep up with the demand for fixes and features now on my own and fear that without other people stepping in to help, `ATK` is going to eventually die.

If anyone wants to add a temporary fix to `ATK` until all the relevant services have been fixed I'll be happy to consider it.

Thanks
Tom

**Comment by nemchik** [comment]
Sonarr should be fixed at this point. If anyone is able to confirm that using ATK's update menu fixes Sonarr this issue can be closed. Mine was already updated before the issue hit so I never had a problem or I'd confirm myself :)

**Comment by campbc** [comment]
I updated mine with Atomic Toolkit (ATK) manual update script and it is now up and running.

**Comment by TommyE123** [comment]
Super! 
Thanks @campbc for letting us know.

I recon we are ok with this now but I'll keep it open just a bit longer so anyone with issues can see it should be ok now. 

If anyone wants to also confirm, it would be handy to know.

Thanks everyone for being patient but this one was slightly out of our hands!

Tom

**Comment by TommyE123** [comment]
@vrokolos are you working OK now? If so i'll close this off.

**Comment by vrokolos** [comment]
Yes thanks
