### ISSUE TITLE
Software Configuration

### ISSUE THREAD

**Issue by symbios24** [htpcBeginner/AtoMiC-ToolKit#245]
Hello, does this script automatically configures HTPC Manager with the installed softare so you dont have manual to setup it?

I mean if i install transmission with HTPC Manager do i need to configure from HTPC Manager Transmission? etc: ip/port?

**Comment by TommyE123** [comment]
I'm afraid yes you would need to configure `HTPC Manager` with the other services you setup. This sort of feature could possibly be added in future though. I would suggest adding it as a feature request at the [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit) and then it will be on the radar of things to add.

Thanks
Tom
