### ISSUE TITLE
Radarr and jackett installs

### ISSUE THREAD

**Issue by erfly7** [htpcBeginner/AtoMiC-ToolKit#246]
## The problem
Radarr and Jackett not working install and on details page always say inactive and localhost never work?
### My Linux distribution and version is: 

- Ubuntu Desktop 16.04.5

## I'm seeing this behaviour on: 
- A fresh install

### Link to install logs
No idea where to find this
### I'm not a dummy, so I've checked these!
- I'm using the latest version of AtoMiC-ToolKit. 
- All my Linux distro packages are up to date and I don't see any errors while updating. 
- I've checked there are no current open issues relating to my problem!

**Comment by Mohammed-JS-Khan** [comment]
Hi there. I had just gone through this earlier today and ended up solving the problem.

First off, it isn't a problem with `ATK`. It also is not a problem with `Mono` as some people were saying reverting to `Mono v5.8` from `v5.10` solves the problem.

What the issue actually is, is that the latest `NLog` release is broken. So here's what everyone is doing to fix it:

1. Backup the `NLog.dll` files from within `/opt/NzbDrone/` (this is for sonarr) and `/opt/radarr/` (for radarr) and whatever the `jackett` `/opt/` folder is (never used it) to a safe location on their box (`home` folder or something, just in case you need to revert)

2. Download the hotfixed `NLog.dll` file from here: [https://download.sonarr.tv/hotfixes/regression-mono-5.10/NLog.dll.gz](https://download.sonarr.tv/hotfixes/regression-mono-5.10/NLog.dll.gz)

3. Extract and copy the downloaded `NLog.dll` to `/opt/NzbDrone/`, `/opt/radarr`, and whatever the `jackett` directory is.

4. Restart for good measure

Sources:
[https://github.com/Sonarr/Sonarr/issues/2431](https://github.com/Sonarr/Sonarr/issues/2431)
[https://github.com/htpcBeginner/AtoMiC-ToolKit/issues/244](https://github.com/htpcBeginner/AtoMiC-ToolKit/issues/244)

Hope that helps!

**Comment by nemchik** [comment]
Latest version of Jackett (released just this morning) should be fixed. Can anyone confirm that using ATK's menu to update Jackett resolves the issue? This issue should stay open until Radarr is resolved as well.

**Comment by TommyE123** [comment]
You can monitor the progress of the fix https://github.com/Radarr/Radarr/issues/2585 here.

**Comment by erfly7** [comment]
So better to wait until atk updates?  sonarr seems to be working for me was just jackett and radarr

**Comment by nemchik** [comment]
@erfly7 ATK doesn't need to make any changes. Once Radarr fixes their issues ATK can install their update for you and then it'll work.

**Comment by nemchik** [comment]
Radarr looks to be fixed now. Can anyone confirm?

**Comment by nemchik** [comment]
Ok there's an actual release now. https://github.com/Radarr/Radarr/releases/tag/v0.2.0.995

Using atk to update radarr should fix and close this issue.

**Comment by TommyE123** [comment]
Hi @erfly7, 

How are you getting on? 
Am I OK to close this now?

Thanks
Tom

**Comment by ismay** [comment]
> Using atk to update radarr should fix and close this issue.

Yup, that fixed it for me.

**Comment by TommyE123** [comment]
Great stuff. I'll close this.
Thanks for logging the original issue.
