### ISSUE TITLE
sickrage-installer.sh  |  Could not copy autoProcess.cfg

### ISSUE THREAD

**Issue by tootflap** [htpcBeginner/AtoMiC-ToolKit#25]
Appears to be an issue on the git-pull request (line 115).
No autoProcessTV/autoProcessTV.cfg file pulled from Git
Installer errors-out.

**Comment by htpcBeginner** [comment]
Fixed in development branch. The script now looks for autoProcessTV.cfg.sample file. If not found, it moves on with installation without erroring out.
