### ISSUE TITLE
Transmission Issues

### ISSUE THREAD

**Issue by eangulus** [htpcBeginner/AtoMiC-ToolKit#253]
## The problem
Installing Transmission via AtoMiC-ToolKit since Transmission 2.93 is now broken.

There is a known issue with Transmission and the problem extends from people installing the PPA version. I am not an expert by any means, but basically, I interpreted that one should not install via PPA as transmission devs have no control over this. It should be installed directly from transmission.

It seems AtoMiC-ToolKit installs using PPA. I came across the failed startup bug and tried reinstalling transmission using AtoMiC-ToolKit and the bug persisted. It wasn't until I found the issue on transmission and a solution that I managed to fix it.

I believe that AtoMiC-ToolKit should change the way it installs transmission to avoid PPA.
See the issue at transmission here:
https://github.com/transmission/transmission/issues/537

- Ubuntu Server 16.04.3

**Comment by TommyE123** [comment]
Hi, Thanks for logging this.

I stumbled across this issue yesterday by accident and came to exactly the same conclusion for the issue as you did.

I've already created a dev branch and made the changes along with a few minor cosmetic improvements. I just need to change how it updates `Transmission` to check if `Type=Simple` is present in the `transmission-daemon-override.conf` which won't take long. I simply ran out of time yesterday! 

The `ppa` we currently use has been rock solid for years and this is the first time we've had an issue. If we didn't use it we would be stuck on a much older version of `Transmission` so I'm reluctant to change it. We've also recently had issues with other services failing which were using the official install methods so it shows it can happen to any service at anytime!!

We currently use `Travis-CI` for checking everything installs correctly on every commit of code we make. Unfortunately it currently only supports Ubuntu 14.04 which uses the old `init.d` scripts to start services. This is issue with Transmission wouldn't have caught that annoyingly. We need to find another free online service that we can run our tests against a later Ubuntu version.. ie 16.04 (if anyone has any ideas on that please do shout!)

I'll be looking to push the fix today or latest tomorrow for this.

Thanks again
Tom

**Comment by TommyE123** [comment]
This should be fixed now :-) 

If you still have it installed just do a manual update. If not then a fresh install should be ok as well.

Please report back with how you get on.

regards
Tom

**Comment by TommyE123** [comment]
I believe this is now fixed. If you run into anymore issues please can you open another issue.

Thanks
Tom
