### ISSUE TITLE
Files downloaded with rTorrent disappear from my server.

### ISSUE THREAD

**Issue by Arck0s** [htpcBeginner/AtoMiC-ToolKit#256]
## New features
Please visit http://feathub.com/htpcBeginner/AtoMiC-ToolKit

## The problem
Hello,
I have a big problem, the files downloaded with rTorrent disappear from my server.
When I launch a download with ruTorrent, after a certain time (it's never the same from what I've seen) my files disappear from my server, but if these downloads are launched with Radarr, then there are no worries, the files remain on the server, but disappear under ruTorrent.

I tried updating my Debian, updating ATK, re-installing my server and ATK, but I still have the same problem.

On this new installation I Organizr, Muximux (I know it's the same thing, it was to find the best), Glance, Radarr, Rtorrent / ruTorrent, Jackett.

### My Linux distribution and version is: 
- Debian 9 up to date
- ATK too
### I'm seeing this behaviour on: 
- A fresh install
- On my previous installation it worked, and overnight the problems started

Thank you for your help

**Comment by nemchik** [comment]
Can you post your config for rtorrent here? (Remove any sensitive info)

**Comment by Arck0s** [comment]
Thank for your help

`# enable/modify the options as needed. Remember to
# uncomment the options you wish to enable.

scgi_port = 127.0.0.1:5000

# Maximum and minimum number of peers to connect to per torrent.
#
#throttle.min_peers.normal.set = 40
#throttle.max_peers.normal.set = 100

# Same as above but for seeding completed torrents (-1 = same as downloading)
#
#throttle.min_peers.seed.set = 10
#throttle.max_peers.seed.set = 50

# Maximum number of simultanious uploads per torrent.
#
#throttle.max_uploads.set = 15

# Global upload and download rate in KiB. "0" for unlimited.
#
#throttle.global_down.max_rate.set_kb = 0
#throttle.global_up.max_rate.set_kb = 0

# Default directory to save the downloaded torrents.
#
directory.default.set = ~/Downloads/rtorrent/completed

# Default session directory. Make sure you don't run multiple instance
# of rtorrent using the same session directory. Perhaps using a
# relative path?
#
session.path.set = ~/Downloads/rtorrent/session

# Watch a directory for new torrents, and stop those that have been
# deleted.
#
schedule2 = watch_directory,5,5,load.start=~/Downloads/rtorrent/watch/*.torrent
#schedule2 = untied_directory,5,5,stop_untied=

# Close torrents when diskspace is low.
#
schedule2 = low_diskspace,5,60,close_low_diskspace=100M

# The ip address reported to the tracker.
#
#network.local_address.set = 127.0.0.1
#network.local_address.set = rakshasa.no

# The ip address the listening socket and outgoing connections is
# bound to.
#
#network.bind_address.set = 127.0.0.1
#network.bind_address.set = rakshasa.no

# Port range to use for listening.
#
#network.port_range.set = 45000-65000

# Start opening ports at a random position within the port range.
#
#network.port_random.set = no

# Check hash for finished torrents. Might be usefull until the bug is
# fixed that causes lack of diskspace not to be properly reported.
#
#pieces.hash.on_completion.set = no

# Set whether the client should try to connect to UDP trackers.
#
#trackers.use_udp.set = no

# Alternative calls to bind and ip that should handle dynamic ip's.
#
#schedule2 = ip_tick,0,1800,ip=rakshasa
#schedule2 = bind_tick,0,1800,bind=rakshasa

# Encryption options, set to none (default) or any combination of the following:
# allow_incoming, try_outgoing, require, require_RC4, enable_retry, prefer_plaintext
#
# The example value allows incoming encrypted connections, starts unencrypted
# outgoing connections but retries with encryption if they fail, preferring
# plaintext to RC4 encryption after the encrypted handshake
#
# protocol.encryption.set = allow_incoming,enable_retry,prefer_plaintext

# Enable DHT support for trackerless torrents or when all trackers are down.
# May be set to "disable" (completely disable DHT), "off" (do not start DHT),
# "auto" (start and stop DHT as needed), or "on" (start DHT immediately).
# The default is "off". For DHT to work, a session directory must be defined.
# 
# dht.mode.set = auto

# UDP port to use for DHT. 
#
#dht.port.set = 6881

# Enable peer exchange (for torrents not marked private)
#
#protocol.pex.set = yes

# Set downlad list layout style. ("full", "compact")
#
#ui.torrent_list.layout.set = "full"
`

**Comment by nemchik** [comment]
Have you checked in both your completed folder and your session folder?

**Comment by Arck0s** [comment]
Yes, I searched in my all files in /home

**Comment by nemchik** [comment]
I'm a bit stumped on this one. I am wondering if this issue is something to do with the way ATK handles rtorrent or if this is an issue with rtorrent itself. There is information about an IRC help channel at the bottom of this page https://github.com/rakshasa/rtorrent/wiki Maybe they have seen this issue before and could help? If they do have a solution we'd definitely like to know if there's something we could do help prevent it from happening to others.

**Comment by Arck0s** [comment]
Hello,
I'll see, thank you.
Since I posted, I use deluge and no worries.
Thank you

**Comment by TommyE123** [comment]
Closing as no longer required. If anyone else is having the same issues, Please let us know.
