### ISSUE TITLE
RFE: Add tvheadend TV server

### ISSUE THREAD

**Issue by ludi113** [htpcBeginner/AtoMiC-ToolKit#264]
## New features
Please visit http://feathub.com/htpcBeginner/AtoMiC-ToolKit
Feature added to feathub

## The enhancement request 

Since the Atomic Toolkit supports the installation of Kodi, I would like to ask you whether you could consider also adding the installation of a TV server. In fact, the TV server would probably fit in quite well, as:

 - Kodi can act as a tvheadend client
 - once installed, tvheadend is configured and administered through the web interface it provides itself
 - it supports the reception of satellite, terrestrial and cable broadcasts (locally: tv-card, tv-stick,... ; remotely: satip, hdhomerun,...)
 - ... 

Site: 
https://tvheadend.org/ 

debs for ubuntu and debian: 
https://tvheadend.org/projects/tvheadend/wiki/AptRepository 

### My Linux distribution and version is: 
n.a.

### I'm seeing this behaviour on: 
n.a. 

### Link to install logs
n.a.

**Comment by nemchik** [comment]
It seems you have posted your request to FeatHub already https://feathub.com/htpcBeginner/AtoMiC-ToolKit/+40

Thank you for posting. I think we can close this issue here on GitHub and keep track of the feature request on FeatHub.

**Comment by ludi113** [comment]
Thanks for the quick reply. 

In fact, I wondered whether the post on FeatHub would be sufficient, so I preferred to post it here, too; especially also because on FeatHub all the newlines seem to have been removed and thus it is harder to read. 

I don't mind if you close this thread if you think it appropriate.

**Comment by nemchik** [comment]
@ludi113 if your request on FeatHub gets lots of votes or if it's fairly simple and quick to include it'll be moved up higher on our priority list. We try to keep the issue tracker here used just for problems and not feature requests.

Thanks :)
