### ISSUE TITLE
NZBHydra v1 No Longer in Development, Can ATK be Updated for NZBHydra2?

### ISSUE THREAD

**Issue by jd4883** [htpcBeginner/AtoMiC-ToolKit#289]
## New features
Can NZBHydra be replaced with NZBHydra2 in ATK? NZBHydrav1 is no longer in development and has been replaced with NZBHydra2 (which is awesome by the way)

## The problem
See feature request

### My Linux distribution and version is: 
Ubuntu 16.04

### I'm seeing this behaviour on: 
- Any install fresh or not

### I'm not a dummy, so I've checked these!
- I'm using the latest version of AtoMiC-ToolKit. 
- All my Linux distro packages are up to date and I don't see any errors while updating. 
- I've checked there are no current open issues relating to my problem!

**Comment by nemchik** [comment]
New features are currently not being added to ATK. Please see the readme.
