### ISSUE TITLE
Lazy Librarian service fails to start, requires samba which was not installed

### ISSUE THREAD

**Issue by rjshaver** [htpcBeginner/AtoMiC-ToolKit#301]
## New features
Please visit http://feathub.com/htpcBeginner/AtoMiC-ToolKit

## The problem
On a new install of Ubuntu 18.04 Bionic, I performed a new install of AtoMiC-ToolKit.  I updated Ubuntu, all packages and then attempted to install Lazy Librarian.  Everything worked, but would not start the service.  Checking logs showed that samba was not installed and would not start without it.

### My Linux distribution and version is: 
- Ubuntu Desktop 18.04 Bionic

### I'm seeing this behaviour on: 
- A fresh install

### Link to install logs
Sorry, have not been able to do this part.

### I'm not a dummy, so I've checked these!
yes - I'm using the latest version of AtoMiC-ToolKit. 
yes - All my Linux distro packages are up to date and I don't see any errors while updating. 
checked- I've checked there are no current open issues relating to my problem! 
one other issue was similar but does not describe successful installation but failed to start service

SOLUTION:  Put a section in the install of Lazy Librarian to check for samba and if not installed, then 'sudo apt install samba'

**Comment by nemchik** [comment]
The devs have all stopped maintaining ATK and have moved onto Docker. Here is a project (noted in the readme) that has LazyLibrarian running in docker and operates very similar to ATK.

https://github.com/GhostWriters/DockSTARTer

**Comment by rjshaver** [comment]
Thx.
