### ISSUE TITLE
changed the port of sonarr in the program. sonarr still works fine but the toolkit doesn't like that i changed the ports

### ISSUE THREAD

**Issue by Menz01** [htpcBeginner/AtoMiC-ToolKit#303]
hello this is my first time using the toolkit and it was awesome. however, i like to change the ports of the programs and i changed sonarr from port 8989 to another port. i have no issues running sonarr on another port, but the toolkit does not like that i changed the port and now the sonarr tasks dont run right. what do i do if i change the ports in the programs after they are installed?

**Comment by Menz01** [comment]
ughhh....  does that mean i need to blow my VM away and start over?

**Comment by nemchik** [comment]
Not at all. You can install DockSTARTer on top of ATK and transfer all your configs into the docker app folders.

**Comment by Jpalmer771** [comment]
Delete an reinstall an try port 8080

-------- Original Message --------

**Comment by nemchik** [comment]
Can you tell me which version of Ubuntu and what hardware you are trying to run on? Also did you complete the prerequisites before trying to run DockSTARTer? (The readme shows the prerequisites before the DockSTARTer commands)

If you continue to have issues you can join our discord server and we can help https://discord.gg/YFyJpmH

**Comment by Jpalmer771** [comment]
I was informed to tell you to try dockstarter

-------- Original Message --------

**Comment by Menz01** [comment]
@nemchik i am using Ubuntu 18.04 desktop. i just deleted my VM and built a fresh new one. i am going to try again. and to answer your questions i did do the perquisites. and i am about to do them again. i will join discord as well cause as i said i am a huge noob with linux so i am SURE i will need help
