### ISSUE TITLE
setup.sh doesn't run...

### ISSUE THREAD

**Issue by lhjk** [htpcBeginner/AtoMiC-ToolKit#32]
A noob here.
Installed ubuntu server and tried this script.
After going to AtoMic-ToolKit directory and entering [sudo ./setup.sh],  below error comes out.

[sudo: ./setup.sh: command not found]

when I type [ls] in the directory, setup.sh is there but in grey.

Can anyone help?

**Comment by eangulus** [comment]
Having same issue.

**Comment by eangulus** [comment]
Change the permissions and give execute to user and group.

**Comment by htpcBeginner** [comment]
Yes, I will fix it shortly. Mean as @eangulus suggested do this:

Go into AtoMiC-ToolKit directory and issue the following command:

sudo chmod 755 *

Then run setup: sudo ./setup.sh

**Comment by htpcBeginner** [comment]
Fixed in the latest overhaul.
