### ISSUE TITLE
Feature Request - PyLoad Support

### ISSUE THREAD

**Issue by htpcBeginner** [htpcBeginner/AtoMiC-ToolKit#37]
http://forum.htpcbeginner.com/showthread.php?tid=164

**Comment by TommyE123** [comment]
Jackett has now been added. I've updated the title to reflect we still need to look at PyLoad.

**Comment by TommyE123** [comment]
pyLoad has now been added :-). 
It would be really appreciated if anyone can confirm it installs and works OK on their system? 
Thanks
Tom

**Comment by TommyE123** [comment]
No sooner have I added this, It appears they've changed how it needs to be installed. I'll get round to fixing this over the next few days.

**Comment by TommyE123** [comment]
I've now fixed this again and will push the changes up to the master branch soon.

**Comment by TommyE123** [comment]
Changes are now in the master branch.
