### ISSUE TITLE
Feature Request - Emby Server

### ISSUE THREAD

**Issue by eangulus** [htpcBeginner/AtoMiC-ToolKit#38]
Would love to see Emby Server added to the install list.

**Comment by TommyE123** [comment]
I've tested installing on Mint and Raspbian however I've not tried to add any media or playback anything.
Please could someone report back and let me know if this application works ok which would be really appreciated.

Tom

**Comment by TommyE123** [comment]
I've not heard any bad feeback on this so will assume its ok. Please log an issue if anyone finds a problem.

Thanks
