### ISSUE TITLE
Extend to RPi2 / Raspbian

### ISSUE THREAD

**Issue by htpcBeginner** [htpcBeginner/AtoMiC-ToolKit#40]
http://forum.htpcbeginner.com/showthread.php?tid=164&pid=279#pid279

**Comment by ezraholm50** [comment]
Might aswell include the new RaspberryPI3 (64bit, 1.2 ghz, 1gb ddr2), and maybe the RPI Zero?

**Comment by TommyE123** [comment]
I am slowly going through updating all the apps to support Raspbian. This should allow any Raspberry pi to use the toolkit.

**Comment by TommyE123** [comment]
Every program now supports Raspbian as standard and going forward that will be a prerequisite for all new programs.
