### ISSUE TITLE
Add support for Deluge

### ISSUE THREAD

**Issue by htpcBeginner** [htpcBeginner/AtoMiC-ToolKit#5]

**Comment by carrigan98** [comment]
I have a start on this if you want me to add it to the dev branch.

**Comment by htpcBeginner** [comment]
@carrigan98 awesome. Please do. Next few days I am quite busy but I can work on it later. Btw, do you have a donation link or paypal...would like to buy you a beer for your hard work :-)

**Comment by htpcBeginner** [comment]
Added to dev branch.
