### ISSUE TITLE
Cant reach certain programs

### ISSUE THREAD

**Issue by ezraholm50** [htpcBeginner/AtoMiC-ToolKit#64]
Hey, 

First of, I really love the toolkit, great work!

I recently installed the current master, installed sab, couch, sonarr, headphones, webmin, htpc manager with it. 

Now i can only access couchpotato, webmin and htpc manager. I used the access tools to show the details, and I cant connect to any of the addresses listed there. (thats for headphones, sab and sonarr)

Also tried a fresh OS (ubuntu 14.04 server vm) but I keep having the same error, ERR_CONNECTION_REFUSED

I run the toolkit as my sudo user, also tried root, doesn't help..
(With previous versions, cant recall which, there where no problems at all)

I' d really like some help trouble shooting, as I want to keep using the toolkit.
I will also help out testing the toolkit on the RPI2, 3 and Zero in a few weeks when my RPI/cloud project is finished!

**Comment by TommyE123** [comment]
Sorry that its taken till now to come back to you. 
Are you still using the toolkit and if so are you still having any issues I can help with?

**Comment by ezraholm50** [comment]
No problem, the issues where resolved but now on Ubuntu server 16.04 they arise again.

When I reboot the machine I can access anything for about an hour to half an hour. Now after that period everything is inaccessible again and I need to reboot. 
I run an OpenVPN client on the machine that drops the connection if there's no link on tun0. That is not the case for the access fail I encounter.

**Comment by TommyE123** [comment]
Hi,

This is not going to be easy to track down what the problem is. I'm currently working my way through all the existing applications to convert them over to support the newer systemd startup scripts as default. I doubt that's what's causing the issue here but could be worth a shot to rule it out. I can't help but suspect its related to the openvpn setup you have possibly knocking out something on the firewall once it goes down? Have you tried asking on the forms either at your VPN provider or maybe try our forum to see if anyone else is having this issue? I'm also assuming that every program you have running is then no longer accessible and not just the odd 1 or 2?

Sorry I can't be of more help on this. If anyone else has any ideas please feel free to comment!!

Tom

**Comment by ezraholm50** [comment]
No problem thanks gorgeous your time anyway. Will start a fresh install anyway without vpn to debug.

**Comment by ezraholm50** [comment]
Lol can't edit on android, gorgeous must be for... haha

**Comment by TommyE123** [comment]
No problem!

The only application left for me to update is Transmission which I'm very nearly done on as well. If your doing a fresh install I'd very much be interested in how you get on. I'm then planning on adding more programs. 
If there's anything you want next and I can get it working, Then in return for a bit of testing and feedback give me a shout!

**Comment by ezraholm50** [comment]
No problem, what apps are left? Cause I made some automated scripts for some applications, might be able to provide a blue print for them.

**Comment by TommyE123** [comment]
I think we really need to get Emby and Plex working next to complement the suite of programs we already have though i'm open to anything really. I also need to add a few support programs for example nzbtomedia. I want to do a poll and see what people are using and what they want next which i'll post over the coming days to help focus my efforts.

Im also keen for people to report any bugs!! I'm certain there is some however I've not had time to thrash the programs once they've installed ok!

**Comment by ezraholm50** [comment]
Cool, any link to a community? Sorry for being lazy. 
I have a few minor bugs already. I will change the script a little so it'll write every output and error to a log file as well. Then I'll install everything available on an Ubuntu machine. I'll post it up as soon as its done (could take me a few days, finishing raspberry/nextcloud project first). 

Let me know if you need any web space or testing environments.

Plex (with auto updates) won't be that hard and I'd be glad to help on implementing.

**Comment by TommyE123** [comment]
http://forum.htpcbeginner.com/
I'm kinda new there myself but feel free to message me!
Please hold off transmission till i give the nod. Its not ready yet but will be soon.

Thanks for everything you've offered to help with.
Tom

**Comment by ezraholm50** [comment]
No problem, I'll sign up and check it out. Will do! Got IRC?

You're welcome!
