### ISSUE TITLE
Feature Request - Jackett

### ISSUE THREAD

**Issue by eangulus** [htpcBeginner/AtoMiC-ToolKit#68]
How about adding Jackett?

And would be nice to add one of the forks that use Public Indexers like TPB.

**Comment by Dnkhatri** [comment]
Jackett public crashes to much and with almost no updates is not worth it. Adding  cardigann might be the way to go https://github.com/cardigann/cardigann
It does not require mono has simple binary to install and has definitions system where even if a tracker is not built in you could add the trackers if you know a little bit of scripting. Plus its footprint is very small compared to jackett so could be easily installed and run on nas.

**Comment by Dnkhatri** [comment]
Would like to ask for jackett support with definition support jackett alone is enough no need for jackett public

**Comment by TommyE123** [comment]
This has now been added :-) 
Please can you give it a try and report back with the outcome?
Thanks Tom

**Comment by TommyE123** [comment]
I've not heard any bad feeback on this so will assume its ok. Please log an issue if anyone finds a problem.

Thanks

**Comment by Dnkhatri** [comment]
I had installed Jackett manually already used atomic toolkit to backup and then reinstalled it using atomic toolkit. Btw my mono install was updated when I used atomic toolkit to install Jackett didn't when I installed sonaar or radaar using toolkit sometime ago. 
    Maybe you should look into updating mono when installing sonarr and radarr as well.

**Comment by TommyE123** [comment]
Thanks for coming back to me and for pointing this out, its just the sort of feedback I need. Your right they should be updating mono as well so I'll update then shortly shortly.
