### ISSUE TITLE
SabNZB+ Not Installing correctly.

### ISSUE THREAD

**Issue by eangulus** [htpcBeginner/AtoMiC-ToolKit#71]
Clean install of Ubuntu Server 16.0.1 LTS.

Installed SabNZB+ via Atomic, and it won't start. If I go to see access details it tells me its not there or invalid install.

**Comment by gabrielpc1190** [comment]
I have the same problem. I just go to install it again and it then works. Not sure what is not doing on the first time.

**Comment by TommyE123** [comment]
I'm currently working on improving the SABnzbd+ install fixing a few bugs and trying to get it to support Debian, Raspbian and Ubuntu. It currently really only supports Ubuntu so if your thinking of installing this just hold off till I release the updated version in the next few days with any luck!

**Comment by TommyE123** [comment]
I've done some limited testing on Linux mint and Raspbian and seems to be working ok now.
