### ISSUE TITLE
Feature Request - NZBHydra

### ISSUE THREAD

**Issue by nigelhooper** [htpcBeginner/AtoMiC-ToolKit#73]
I appreciate that this is on your wishlist list, but I cant see an issue for it:

Please add consider adding support for [nzbhydra](https://github.com/theotherp/nzbhydra)

**Comment by TommyE123** [comment]
Im going to try and get this working next. Just finishing off getting NZBGet working first.

**Comment by htpcBeginner** [comment]
@TommyE123 Thanks for the contribution. Could you please get in touch with me through the contact form on my site? I might have some good things to share with you :-)

http://www.htpcbeginner.com/contact/

**Comment by TommyE123** [comment]
This has now been added. It should work for Ubuntu, Debian and Raspbian. Any problems or bugs please don't hesitate to log an issue.

Tom
