### ISSUE TITLE
Feature Request - LazyLibrarian

### ISSUE THREAD

**Issue by nigelhooper** [htpcBeginner/AtoMiC-ToolKit#74]
Please consider adding support for the DobyTang branch of [LazyLibrarian](https://github.com/DobyTang/LazyLibrarian) as this branch is still being actively developed.

**Comment by TommyE123** [comment]
Hi Nigel, 
Yesterday my Lazy Librarian implementation was pulled into the main branch. Sorry it's taken a while but i had to overcome a few issues with LL itself which have now been fixed. If you still wanted to try it out please could u give it a shot and update us with the results? 

Im keen to know what you or anyone else reading this installed it on and if it worked ok!

Thanks
Tom

**Comment by nigelhooper** [comment]
Hi Tommy,
Thanks for you work.  I have updated Atomic and run the installer for LL, it didn't give me any errors.

I then selected the LL access details tab and it said:
> Error! /opt/lazylibrarian/lazylibrarian.ini not found. lazylibrarian not installed or incompatible installation.
Exiting. If lazylibrarian is installed, use sudo ./setup.sh to start it.

I tried opening the default LL url http://127.0.0.1:5299 and it didn't display anything

In /opt I have a directory called lazylibrarian and also a lazylibrarian_01-14-2017_11-16

The lazylibrarian directory contains several files and directories

I tried rerunning the installer again with the same result.

I rebooted and the url still timed out.

I assume  lazylibrarian_01-14-2017_11-16 is a temporary file can the script delete it?

I am running Ubuntu 16.04.1 LTS

Thanks,

Nigel

**Comment by TommyE123** [comment]
Hi Nigel, firstly thanks for giving it a try. The error message is slightly miss-leading in this case i hope. Ive made it more helpful in my branch but not pushed it up to the main branch yet. With Lazy Librarian it doesnt create the config.ini file until you make a save in the ui so until that happens the access details wont work.

Can you give me the results of typing:
sudo systemctl status lazylibrarian.service

Does it say its running? 

By default it should allow you to connect from another pc on your network. Might be worth giving that a try by using the linux pc ipaddress.

The file with a date on the end is a backup that gets created if you reinstall over the top with uninstalling and isnt really anything to worry about.

Im sure its something silly that we cant sort out.

Tom

**Comment by TommyE123** [comment]
Sorry can sort out rather!!

**Comment by nigelhooper** [comment]
I have run:
sudo systemctl status lazylibrarian.service

and it says:
active (running)

I wasn't entirely truthful on my earlier reply, I am actually running it on a remote server and trying to connect via open vpn and suspect that is why I can't connect.  I am guessing I need to bind it to 0.0.0.0 first.

**Comment by nigelhooper** [comment]
I have been able to connect by, stopping the service, creating config.ini with
[General]
http_port = 5299
http_host = 0.0.0.0
and then restarting the service

I have been able to add a book and am trying to work out if I can get it to write out the rest of the config file.

**Comment by nigelhooper** [comment]
I have entered a username and password in the config via the gui and restarted.  My config.ini file hasn't changed but I now have a lazylibrarian.ini file with all the default settings in, which is strange as my  other instance of LL doesn't have this file.

**Comment by TommyE123** [comment]
Really pleased you got it working,

The reason for lazylibrarian.ini rather then config.ini is that Lazy Librarian has changed their config file name so the config.ini is the old name.

The config.ini file you created wont be used at all as the systemd is setup to point to lazylibrarian.ini. You can safely just delete the config.ini you created. 

If you have any further issues give me a shout :-)

**Comment by TommyE123** [comment]
I'm going to suggest we close this issue now as this has now been implemented and i'm not aware of any other issues.
