### ISSUE TITLE
sabnzbdplus init script could be wrong

### ISSUE THREAD

**Issue by gabrielpc1190** [htpcBeginner/AtoMiC-ToolKit#75]
Linux Mint 18:
When I do a reboot on the system and I have a queue full of downloading jobs, the queue is distroyed and next time sabnzbdplus starts I have to go to status and add every download again because they are as orphaned jobs.
If you see the recommended way of running sabnzbdplus on the [Wiki](https://sabnzbd.org/wiki/installation/install-as-a-unix-daemon) a daemon, it sends an http request to the url using the API to stop the sabnzbdplus and doing it this way the queue will not be destroyed.
I am not sure how it is stopped right now because I don't really understand the init script, but if anyone understand it can confirm if its the right way of stopping the daemon.

**Comment by gabrielpc1190** [comment]
This may be a good example for the init script. Just need to figure out how to get the API from the config file.

```
#! /bin/sh
### BEGIN INIT INFO
# Provides:          sabnzbd
# Short-Description: start/stop sabnzbd web interface
### END INIT INFO


USER="username"
HOME="/home/username"
SAB_IP="192.168.2.105:8080"
SAB_USER="login"
SAB_PASS="password"
SAB_APIKEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

case "$1" in
start)
  echo "Starting SABnzbd."
  /usr/bin/sudo -u $USER -H /usr/bin/sabnzbdplus -d -f $HOME/.sabnzbd/sabnzbd.ini
;;
stop)
  echo "Shutting down SABnzbd."
  /usr/bin/wget -q --delete-after "http://$SAB_IP/sabnzbd/api?mode=shutdown&ma_username=$SAB_USER&ma_password=$SAB_PASS&apikey=$SAB_APIKEY"
;;
*)
  echo "Usage: $0 {start|stop}"
  exit 1
esac

exit 0
```

**Comment by gabrielpc1190** [comment]
I did an script for myself and its working. I took parts from everywhere on internet. Please be free to use it as an example or for the Atomic toolkit. I am not an expert but tried so many times until I made it work. Please correct any part of it that it's wrong.

`#! /bin/sh
### BEGIN INIT INFO
# Provides:          sabnzbdplus
# Required-Start:
# Required-Stop:
# Should-Start:       dbus avahi network-manager wicd
# Should-Stop:        dbus avahi network-manager wicd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SABnzbd+ binary newsgrabber
# Description:       SABnzbd+ is a web-based binary newsgrabber with nzb
#                    support, designed to download files from Usenet.
#                    This script provides that functionality as a system
#                    service, starting the program on boot.
### END INIT INFO

USER="changetoyouruser"
HOME="/home/$USER"
SAB_IP="127.0.0.1:8080"
SAB_APIKEY="insertyourapikey"
DAEMON="/usr/bin/sabnzbdplus"
SETTINGS="$HOME/.sabnzbd/sabnzbd.ini"

##------------------------------------------------------------------------##
case "$1" in
start)
  echo "Starting SABnzbd."
  /usr/bin/sudo -u $USER -H $DAEMON -d -f $SETTINGS
;;
stop)
  echo "Shutting down SABnzbd."
  /usr/bin/wget -q --delete-after "http://$SAB_IP/sabnzbd/api?mode=shutdown&amp;apikey=$SAB_APIKEY"
;;
*)
  echo "Usage: $0 {start|stop}"
  exit 1
esac

exit 0`

**Comment by TommyE123** [comment]
I've updated SABnzbd+ to use systemd as default however it does still fallback to init.d if your distro doesnt support it. Can anyone confirm the init.d script is working for them in the new Toolkit version?

**Comment by TommyE123** [comment]
I've not heard any bad feeback on this so will assume its ok. Please log an issue if anyone finds a problem.

Thanks
