### ISSUE TITLE
Light/Dark color scheme request

### ISSUE THREAD

**Issue by nickveldrin** [htpcBeginner/AtoMiC-ToolKit#77]
Hello,

This can be super low priority, but i run my terminal sessions white background and black text, but when using the scripts, it will use yellow text or green text which does not display very well on the light background.

Could it be possible to request a Light or Dark color scheme upon startup for folks that use inverted colors?

**Comment by ZaLiTHkA** [comment]
Perhaps this could be done automatically with an alternate colour scheme, which could be loaded conditionally based on the current terminal background colour?

Just had a quick look and it seems it's possible to [detect this using xterm](http://stackoverflow.com/questions/2507337/is-there-a-way-to-determine-a-terminals-background-color).

**Comment by TommyE123** [comment]
Thanks for pointing this out. I like the idea of having 2 colour schemes depending on the terminal colour. I can certainly look into this. However my only concern will be the time required to get it working, change everything over and potential issues that could arise. If anyone fancies taking this on that would be really handy!

**Comment by TommyE123** [comment]
Hi, 
I've changed the colours slightly to try and improve using it on different backgrounds. I do still see the benefits of this so happy to keep this idea open.

However, I've now moved the feature requests over to [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit)

Could you please vote for this there so we can start getting a feel for what people would like to be worked on next.

Thanks
