### ISSUE TITLE
Transmission and SABnzbd replacing username failed

### ISSUE THREAD

**Issue by htpcBeginner** [htpcBeginner/AtoMiC-ToolKit#8]
http://www.htpcbeginner.com/atomic-toolkit/#comment-4157

After installing Transmission i get this error in the end:

—>Making some configuration changes…
sed: can’t read /etc/init.d/transmission-daemon: No such file or directory
Replacing daemon username in init failed.

I also have the similar problem when trying to install SABNZB.

—>Making some configuration changes…
sed: can’t read /etc/default/sabnzbdplus: No such file or directory
Replacing username in default failed.

You can help ?

**Comment by htpcBeginner** [comment]
Could not replicate issues on Ubuntu 14.04.02.

**Comment by rroethof** [comment]
reopen please. replicatable on ubuntu 15.04

**Comment by harroschoon** [comment]
yep same problem here... only i have 14.04.01...

**Comment by harroschoon** [comment]
Did clean install update and upgrade hot 14.04.02 and now it al works

Op vrijdag 2 oktober 2015 heeft Anand Subramanian <notifications@github.com>
het volgende geschreven:

> Reopened #8 <https://github.com/htpcBeginner/AtoMiC-ToolKit/issues/8>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/htpcBeginner/AtoMiC-ToolKit/issues/8#event-424813110>.
>


-- 
Harro Schoon

**Comment by htpcBeginner** [comment]
Thanks for confirming @harroschoon. Will test on 15.04 soon.

**Comment by ericwooley** [comment]
It's super annoying, and hard to debug. Seems like transmission-daemon writes it's settings out on quit, and I can't seem to find a way to keep it dead long enough to edit the file.

**Comment by htpcBeginner** [comment]
Latest test on 14.04.03 worked. So closing for now.
