### ISSUE TITLE
Radarr support

### ISSUE THREAD

**Issue by mrowlinson** [htpcBeginner/AtoMiC-ToolKit#86]
I would love to see Radarr support added. Radarr is a fork of Sonarr for movies similar to CouchPotato.

https://github.com/Radarr/Radarr

**Comment by htpcBeginner** [comment]
Its coming...hang tight.

**Comment by TommyE123** [comment]
This has now been added. If anyone could confirm its working OK for them I'd really appreciate it!

**Comment by Dnkhatri** [comment]
this worked perfectly for me on linu mint

**Comment by TommyE123** [comment]
Excellent news. Thanks for letting me know. If anyone has any issues please don't hesitate to log an issue.
