### ISSUE TITLE
rtorrent + rutorrent in this script and more ideas

### ISSUE THREAD

**Issue by JuezFenix** [htpcBeginner/AtoMiC-ToolKit#9]
Can you add , rtorrent + rutorrent to this script?
Maybe a nice addition would be an instance of MySQL for use in XBMC / kodi ( to share content and more ) .
Many of these programs use a web server, I guess that you use Apache, but it would be good idea if we could choose between ngix, apache or lhttp .

Do you think you can operate in openmediavault (debian derivated)? If you think not , I use OMV to easily share content to Windows / Linux machines, perhaps adding a script of samba, configuring the shared folders

**Comment by blackley** [comment]
Hi ya,

Any progress on rtorrent and rutorrent or alterative webui for rtorrent?

**Comment by TommyE123** [comment]
I can certainly look into this in the near future. I currently have 4 programs left in the existing toolkit to update to the new format of scripts to support most Ubuntu and Debian variants. Once that's done and all the framework in place to add more programs easily i''ll consider adding anything within reason. :-)

**Comment by blackley** [comment]
Hi @TommyE123 do you happen to have an eta on this enhancement to this terrific tool?

**Comment by TommyE123** [comment]
Hi @blackley, This is on my list of things to do however there's a few other programs that I think we need to get working first which I'm currently working on. I'll come back to you again in the next few days with a more realistic eta but I'd say in the next few weeks at the moment. Hope this is ok.

**Comment by blackley** [comment]
Hi @TommyE123 Any eta on this feature addition to the toolkit?

**Comment by TommyE123** [comment]
This is proving to be slightly tougher to implement than all the previous applications. I've been looking at how it needs to be setup and started on the scripts however its proving slow progress. For now there is 3 other Bittorrent clients you can install and use with the toolkit whilst you wait. I'll give you another update over the weekend.

Hope this is ok, Sorry its taking so long.
Tom

**Comment by TommyE123** [comment]
This is still on going to get this working. I have created the basic scripts however they are miles away from being ready. Unfortunately, the install process doesn’t fit in very well with our current scripts and needs work to bring them in line to accommodate this application. I also have a few more important bugs in other areas of the Toolkit I need to address.

Again sorry its taking a while to implement this.

**Comment by blackley** [comment]
Hi Tom,

Thanks for the update - i completely understand the needs and requirements you have.  I am happy to wait for you to nut out the issues and look forward to the tool inclusion once it is ready :-)

Cheers,
Darren

**Comment by mgiljum** [comment]
Tommy, I'd be happy to lend a hand on this, just give me a shout.

**Comment by TommyE123** [comment]
Super! Well I've made a good start. What i'll do is check in what I've done in the WIP folder. Then you can move them to the logical locations and carry on? It won't be today though I'm afraid.

**Comment by mgiljum** [comment]
Sounds good. Just give me the word when you're ready for me to take a look.

**Comment by mgiljum** [comment]
Are you looking to have rtorrent and rutorrent be separate from each other? ie, users install can install rtorrent all by itself? or when they select rtorrent, it installs rutorrent along with it?

I ask because I've only used rtorrent a few times but I know there's different front-ends available for it. Users might want the option to install their own?

**Comment by rinzler40oz** [comment]
This is a very popular r/rutorrent script that I've been using for a very long time: 
https://github.com/arakasi72/rtinst 

This may help / can use it in the meantime.

**Comment by mgiljum** [comment]
rtorrent seems to already be a packaged app for ubuntu going back to 12.04. Any reason why we can't use that and make it a dependency of rutorrent?

**Comment by TommyE123** [comment]
I now slightly remember thinking the same thing after I started creating the scripts. I recon def go with it as a dep for rutorrent if you can. However I think my only concern was how far does the package go with startup scripts, configs etc.. Are they required?!? Sorry my minds gone a bit blank from when I was trying to prep it a few weeks ago!

**Comment by mgiljum** [comment]
@TommyE123 Well, again, that would depend on whether you want the script to install both together all the time or if you want users to have the option to install rtorrent separately.

If we bundle them, then we could just make the init script for rutorrent call up rtorrent as well, and stop-start-restart them together.

**Comment by blackley** [comment]
@TommyE123 Hi Tom, and eta on when this will be available?

**Comment by blackley** [comment]
Hi @TommyE123 Any eta on this feature addition to the toolkit?

**Comment by TommyE123** [comment]
Hi Darren,
Sorry i've not got back to you sooner.

I'm the only one writing any code at the moment and am doing this in my spare time. I'm fighting so many fires with other applications breaking. Trying to get continous integration tests sorted to check everything is working correctly everytime I check a change in. This will help make sure i don't accidently break anything!

I don't want to keep you hanging but I will try and get to this. I'm going to have another look over the weekend and see what i can come up with as I think I've added a few features I might be able to use with this as well.

Thanks for your continued support and suggestions.

Tom

**Comment by blackley** [comment]
Hi Tom,

No problems - I completely understand the pressure and the issues you mention.  I wasn't trying to hassle you - just wanted to get an idea on timing is all.

Thanks for all your efforts and your time.

Darren

**Comment by TommyE123** [comment]
Just a quick update to say development on this application has started again and I've made some progress on where I was slightly stuck before from knowledge learned scripting other applications. 
I'll try and keep you updated over the week.

**Comment by TommyE123** [comment]
Quick update. 
I got a bit side tracked with a few other issues but... I have rutorrent installing now on my test PC :-) 
Its still got issues and doesn't work correctly yet but i'm getting there!
Sorry its taken a while but there is a light at the end of this tunnel!

Tom

**Comment by mgiljum** [comment]
Sorry I went MIA, health issues...glad to see you were able to get it going!

**Comment by TommyE123** [comment]
This has now finally been implemented. (I hope!) 
It currently doesnt work correctly on older versions of Linux though.
Please can you give it a try and let me know how you get on. 
Thanks
Tom

**Comment by blackley** [comment]
@TommyE123 - i have installed and started to test  a couple of errors are showing up

[06.05.2017 15:46:05] WebUI started.
[06.05.2017 15:46:05] Bad response from server: (502 [error,getplugins]) Bad Gateway
the above is seen when you first launch the browser instance

The one below is when you attempt to launch the configuration (cog) tool.
[06.05.2017 15:52:20] JS error: [http://192.168.14.253/rutorrent/js/webui.js : 762] Uncaught TypeError: Cannot read property 'rTorrent' of undefined

**Comment by TommyE123** [comment]
Sorry your having issues. Ive tried to test it on as many distros as i could! 

What linux version are you using?

Can you also just try rebooting your machine.

Tom

**Comment by blackley** [comment]
Lubuntu 17.04

On 6 May 2017 at 4:10:41 pm, Tom (notifications@github.com) wrote:

Sorry your having issues. Ive tried to test it on as many distros as i
could!

What linux version are you using?

Can you also just try rebooting your machine.

Tom

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/htpcBeginner/AtoMiC-ToolKit/issues/9#issuecomment-299623803>,
or mute the thread

**Comment by TommyE123** [comment]
Could you come and talk to me on
[![Join the chat at https://gitter.im/htpcBeginner/AtoMiC-ToolKit](https://badges.gitter.im/htpcBeginner/AtoMiC-ToolKit.svg)](https://gitter.im/htpcBeginner/AtoMiC-ToolKit?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

See if we can troubleshoot this and get it sorted.

**Comment by TommyE123** [comment]
Closing as has now been added and not heard of any further issues after working with @blackley to fix  bugs.
